//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.15 at 10:09:56 PM CEST 
//


package cz.stuchlikova.ares.application.stub;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.stuchlikova.ares.standard.stub package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ErrorList_QNAME = new QName("http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1", "Error_list");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.stuchlikova.ares.standard.stub
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KonkurzyVyrovnani2 }
     * 
     */
    public KonkurzyVyrovnani2 createKonkurzyVyrovnani2() {
        return new KonkurzyVyrovnani2();
    }

    /**
     * Create an instance of {@link OdstepneZavody2 }
     * 
     */
    public OdstepneZavody2 createOdstepneZavody2() {
        return new OdstepneZavody2();
    }

    /**
     * Create an instance of {@link cz.stuchlikova.ares.application.stub.Akcie }
     * 
     */
    public cz.stuchlikova.ares.application.stub.Akcie createAkcie() {
        return new cz.stuchlikova.ares.application.stub.Akcie();
    }

    /**
     * Create an instance of {@link XsltErrorList }
     * 
     */
    public XsltErrorList createXsltErrorList() {
        return new XsltErrorList();
    }

    /**
     * Create an instance of {@link KonkurzyVyrovnani }
     * 
     */
    public KonkurzyVyrovnani createKonkurzyVyrovnani() {
        return new KonkurzyVyrovnani();
    }

    /**
     * Create an instance of {@link OdstepneZavody }
     * 
     */
    public OdstepneZavody createOdstepneZavody() {
        return new OdstepneZavody();
    }

    /**
     * Create an instance of {@link OdstepneZavody.OdstepnyZavod }
     * 
     */
    public OdstepneZavody.OdstepnyZavod createOdstepneZavodyOdstepnyZavod() {
        return new OdstepneZavody.OdstepnyZavod();
    }

    /**
     * Create an instance of {@link KomanditniSpolecnici }
     * 
     */
    public KomanditniSpolecnici createKomanditniSpolecnici() {
        return new KomanditniSpolecnici();
    }

    /**
     * Create an instance of {@link ClenskeVklady }
     * 
     */
    public ClenskeVklady createClenskeVklady() {
        return new ClenskeVklady();
    }

    /**
     * Create an instance of {@link Kapital }
     * 
     */
    public Kapital createKapital() {
        return new Kapital();
    }

    /**
     * Create an instance of {@link Kapital.Akcie }
     * 
     */
    public Kapital.Akcie createKapitalAkcie() {
        return new Kapital.Akcie();
    }

    /**
     * Create an instance of {@link ZakladniUdajeOR }
     * 
     */
    public ZakladniUdajeOR createZakladniUdajeOR() {
        return new ZakladniUdajeOR();
    }

    /**
     * Create an instance of {@link ZakladniUdajeOR.Historie }
     * 
     */
    public ZakladniUdajeOR.Historie createZakladniUdajeORHistorie() {
        return new ZakladniUdajeOR.Historie();
    }

    /**
     * Create an instance of {@link Cinnost }
     * 
     */
    public Cinnost createCinnost() {
        return new Cinnost();
    }

    /**
     * Create an instance of {@link AresDotazy }
     * 
     */
    public AresDotazy createAresDotazy() {
        return new AresDotazy();
    }

    /**
     * Create an instance of {@link Dotaz }
     * 
     */
    public Dotaz createDotaz() {
        return new Dotaz();
    }

    /**
     * Create an instance of {@link KlicovePolozky }
     * 
     */
    public KlicovePolozky createKlicovePolozky() {
        return new KlicovePolozky();
    }

    /**
     * Create an instance of {@link Uvod }
     * 
     */
    public Uvod createUvod() {
        return new Uvod();
    }

    /**
     * Create an instance of {@link TypRegistru }
     * 
     */
    public TypRegistru createTypRegistru() {
        return new TypRegistru();
    }

    /**
     * Create an instance of {@link Soud }
     * 
     */
    public Soud createSoud() {
        return new Soud();
    }

    /**
     * Create an instance of {@link TypZmeny }
     * 
     */
    public TypZmeny createTypZmeny() {
        return new TypZmeny();
    }

    /**
     * Create an instance of {@link StavKVZ }
     * 
     */
    public StavKVZ createStavKVZ() {
        return new StavKVZ();
    }

    /**
     * Create an instance of {@link ShodaICO }
     * 
     */
    public ShodaICO createShodaICO() {
        return new ShodaICO();
    }

    /**
     * Create an instance of {@link ShodaRC }
     * 
     */
    public ShodaRC createShodaRC() {
        return new ShodaRC();
    }

    /**
     * Create an instance of {@link ShodaOF }
     * 
     */
    public ShodaOF createShodaOF() {
        return new ShodaOF();
    }

    /**
     * Create an instance of {@link AdresaARES }
     * 
     */
    public AdresaARES createAdresaARES() {
        return new AdresaARES();
    }

    /**
     * Create an instance of {@link VysledekHledani }
     * 
     */
    public VysledekHledani createVysledekHledani() {
        return new VysledekHledani();
    }

    /**
     * Create an instance of {@link PenezniSuma }
     * 
     */
    public PenezniSuma createPenezniSuma() {
        return new PenezniSuma();
    }

    /**
     * Create an instance of {@link Osoba }
     * 
     */
    public Osoba createOsoba() {
        return new Osoba();
    }

    /**
     * Create an instance of {@link Nestandardni }
     * 
     */
    public Nestandardni createNestandardni() {
        return new Nestandardni();
    }

    /**
     * Create an instance of {@link FyzickaOsoba }
     * 
     */
    public FyzickaOsoba createFyzickaOsoba() {
        return new FyzickaOsoba();
    }

    /**
     * Create an instance of {@link PravnickaOsoba }
     * 
     */
    public PravnickaOsoba createPravnickaOsoba() {
        return new PravnickaOsoba();
    }

    /**
     * Create an instance of {@link ErrorARES }
     * 
     */
    public ErrorARES createErrorARES() {
        return new ErrorARES();
    }

    /**
     * Create an instance of {@link Chyba }
     * 
     */
    public Chyba createChyba() {
        return new Chyba();
    }

    /**
     * Create an instance of {@link Okec }
     * 
     */
    public Okec createOkec() {
        return new Okec();
    }

    /**
     * Create an instance of {@link KodOkec }
     * 
     */
    public KodOkec createKodOkec() {
        return new KodOkec();
    }

    /**
     * Create an instance of {@link OdpovedBasic }
     * 
     */
    public OdpovedBasic createOdpovedBasic() {
        return new OdpovedBasic();
    }

    /**
     * Create an instance of {@link VypisBasic }
     * 
     */
    public VypisBasic createVypisBasic() {
        return new VypisBasic();
    }

    /**
     * Create an instance of {@link AdresaDorucovaci }
     * 
     */
    public AdresaDorucovaci createAdresaDorucovaci() {
        return new AdresaDorucovaci();
    }

    /**
     * Create an instance of {@link StavSubjektuCeu }
     * 
     */
    public StavSubjektuCeu createStavSubjektuCeu() {
        return new StavSubjektuCeu();
    }

    /**
     * Create an instance of {@link KategoriePoctuPracovniku }
     * 
     */
    public KategoriePoctuPracovniku createKategoriePoctuPracovniku() {
        return new KategoriePoctuPracovniku();
    }

    /**
     * Create an instance of {@link Stav }
     * 
     */
    public Stav createStav() {
        return new Stav();
    }

    /**
     * Create an instance of {@link Registrace }
     * 
     */
    public Registrace createRegistrace() {
        return new Registrace();
    }

    /**
     * Create an instance of {@link SpisovaZnacka }
     * 
     */
    public SpisovaZnacka createSpisovaZnacka() {
        return new SpisovaZnacka();
    }

    /**
     * Create an instance of {@link PredchoziRegistrace }
     * 
     */
    public PredchoziRegistrace createPredchoziRegistrace() {
        return new PredchoziRegistrace();
    }

    /**
     * Create an instance of {@link PredmetyPodnikani }
     * 
     */
    public PredmetyPodnikani createPredmetyPodnikani() {
        return new PredmetyPodnikani();
    }

    /**
     * Create an instance of {@link cz.stuchlikova.ares.application.stub.PredmetPodnikani }
     * 
     */
    public cz.stuchlikova.ares.application.stub.PredmetPodnikani createPredmetPodnikani() {
        return new cz.stuchlikova.ares.application.stub.PredmetPodnikani();
    }

    /**
     * Create an instance of {@link Ico }
     * 
     */
    public Ico createIco() {
        return new Ico();
    }

    /**
     * Create an instance of {@link ObchodniFirma }
     * 
     */
    public ObchodniFirma createObchodniFirma() {
        return new ObchodniFirma();
    }

    /**
     * Create an instance of {@link Dic }
     * 
     */
    public Dic createDic() {
        return new Dic();
    }

    /**
     * Create an instance of {@link OdpovedRZP }
     * 
     */
    public OdpovedRZP createOdpovedRZP() {
        return new OdpovedRZP();
    }

    /**
     * Create an instance of {@link VypisRZP }
     * 
     */
    public VypisRZP createVypisRZP() {
        return new VypisRZP();
    }

    /**
     * Create an instance of {@link ZakladniUdajeRZP }
     * 
     */
    public ZakladniUdajeRZP createZakladniUdajeRZP() {
        return new ZakladniUdajeRZP();
    }

    /**
     * Create an instance of {@link RegistraceRZP }
     * 
     */
    public RegistraceRZP createRegistraceRZP() {
        return new RegistraceRZP();
    }

    /**
     * Create an instance of {@link ZivnostiRZP }
     * 
     */
    public ZivnostiRZP createZivnostiRZP() {
        return new ZivnostiRZP();
    }

    /**
     * Create an instance of {@link Zivnost }
     * 
     */
    public Zivnost createZivnost() {
        return new Zivnost();
    }

    /**
     * Create an instance of {@link ProvozovnyRZP }
     * 
     */
    public ProvozovnyRZP createProvozovnyRZP() {
        return new ProvozovnyRZP();
    }

    /**
     * Create an instance of {@link Provozovna }
     * 
     */
    public Provozovna createProvozovna() {
        return new Provozovna();
    }

    /**
     * Create an instance of {@link ProvozovaneZivnosti }
     * 
     */
    public ProvozovaneZivnosti createProvozovaneZivnosti() {
        return new ProvozovaneZivnosti();
    }

    /**
     * Create an instance of {@link ProvozovanaZivnost }
     * 
     */
    public ProvozovanaZivnost createProvozovanaZivnost() {
        return new ProvozovanaZivnost();
    }

    /**
     * Create an instance of {@link PravniFormaRZP }
     * 
     */
    public PravniFormaRZP createPravniFormaRZP() {
        return new PravniFormaRZP();
    }

    /**
     * Create an instance of {@link AdresaRZP }
     * 
     */
    public AdresaRZP createAdresaRZP() {
        return new AdresaRZP();
    }

    /**
     * Create an instance of {@link ZivnostenskyUrad }
     * 
     */
    public ZivnostenskyUrad createZivnostenskyUrad() {
        return new ZivnostenskyUrad();
    }

    /**
     * Create an instance of {@link FinancniUrad }
     * 
     */
    public FinancniUrad createFinancniUrad() {
        return new FinancniUrad();
    }

    /**
     * Create an instance of {@link EvidencniCislo }
     * 
     */
    public EvidencniCislo createEvidencniCislo() {
        return new EvidencniCislo();
    }

    /**
     * Create an instance of {@link Stadrs }
     * 
     */
    public Stadrs createStadrs() {
        return new Stadrs();
    }

    /**
     * Create an instance of {@link StadrsDotaz }
     * 
     */
    public StadrsDotaz createStadrsDotaz() {
        return new StadrsDotaz();
    }

    /**
     * Create an instance of {@link StadrsOdpoved }
     * 
     */
    public StadrsOdpoved createStadrsOdpoved() {
        return new StadrsOdpoved();
    }

    /**
     * Create an instance of {@link VysledekDotazu }
     * 
     */
    public VysledekDotazu createVysledekDotazu() {
        return new VysledekDotazu();
    }

    /**
     * Create an instance of {@link SeznamNavracenych }
     * 
     */
    public SeznamNavracenych createSeznamNavracenych() {
        return new SeznamNavracenych();
    }

    /**
     * Create an instance of {@link AdresaUIRSNazvy }
     * 
     */
    public AdresaUIRSNazvy createAdresaUIRSNazvy() {
        return new AdresaUIRSNazvy();
    }

    /**
     * Create an instance of {@link Slovo }
     * 
     */
    public Slovo createSlovo() {
        return new Slovo();
    }

    /**
     * Create an instance of {@link VypisRFO }
     * 
     */
    public VypisRFO createVypisRFO() {
        return new VypisRFO();
    }

    /**
     * Create an instance of {@link KrajRFO }
     * 
     */
    public KrajRFO createKrajRFO() {
        return new KrajRFO();
    }

    /**
     * Create an instance of {@link OkresRFO }
     * 
     */
    public OkresRFO createOkresRFO() {
        return new OkresRFO();
    }

    /**
     * Create an instance of {@link ObecRFO }
     * 
     */
    public ObecRFO createObecRFO() {
        return new ObecRFO();
    }

    /**
     * Create an instance of {@link PrazskyObvodRFO }
     * 
     */
    public PrazskyObvodRFO createPrazskyObvodRFO() {
        return new PrazskyObvodRFO();
    }

    /**
     * Create an instance of {@link MestskaCastRFO }
     * 
     */
    public MestskaCastRFO createMestskaCastRFO() {
        return new MestskaCastRFO();
    }

    /**
     * Create an instance of {@link CastObceRFO }
     * 
     */
    public CastObceRFO createCastObceRFO() {
        return new CastObceRFO();
    }

    /**
     * Create an instance of {@link OdpovedCEU }
     * 
     */
    public OdpovedCEU createOdpovedCEU() {
        return new OdpovedCEU();
    }

    /**
     * Create an instance of {@link VypisCeu }
     * 
     */
    public VypisCeu createVypisCeu() {
        return new VypisCeu();
    }

    /**
     * Create an instance of {@link SubjektCEU }
     * 
     */
    public SubjektCEU createSubjektCEU() {
        return new SubjektCEU();
    }

    /**
     * Create an instance of {@link Msp }
     * 
     */
    public Msp createMsp() {
        return new Msp();
    }

    /**
     * Create an instance of {@link Aceu }
     * 
     */
    public Aceu createAceu() {
        return new Aceu();
    }

    /**
     * Create an instance of {@link KZruseno }
     * 
     */
    public KZruseno createKZruseno() {
        return new KZruseno();
    }

    /**
     * Create an instance of {@link KChyba }
     * 
     */
    public KChyba createKChyba() {
        return new KChyba();
    }

    /**
     * Create an instance of {@link VkPodnet }
     * 
     */
    public VkPodnet createVkPodnet() {
        return new VkPodnet();
    }

    /**
     * Create an instance of {@link VkAdresa }
     * 
     */
    public VkAdresa createVkAdresa() {
        return new VkAdresa();
    }

    /**
     * Create an instance of {@link KKonkurz }
     * 
     */
    public KKonkurz createKKonkurz() {
        return new KKonkurz();
    }

    /**
     * Create an instance of {@link KKlic }
     * 
     */
    public KKlic createKKlic() {
        return new KKlic();
    }

    /**
     * Create an instance of {@link KUpadce }
     * 
     */
    public KUpadce createKUpadce() {
        return new KUpadce();
    }

    /**
     * Create an instance of {@link KEksubj }
     * 
     */
    public KEksubj createKEksubj() {
        return new KEksubj();
    }

    /**
     * Create an instance of {@link KCosoba }
     * 
     */
    public KCosoba createKCosoba() {
        return new KCosoba();
    }

    /**
     * Create an instance of {@link RadkyTextuUsneseni }
     * 
     */
    public RadkyTextuUsneseni createRadkyTextuUsneseni() {
        return new RadkyTextuUsneseni();
    }

    /**
     * Create an instance of {@link SpravceKonkurzuCEU }
     * 
     */
    public SpravceKonkurzuCEU createSpravceKonkurzuCEU() {
        return new SpravceKonkurzuCEU();
    }

    /**
     * Create an instance of {@link OdpovedOR }
     * 
     */
    public OdpovedOR createOdpovedOR() {
        return new OdpovedOR();
    }

    /**
     * Create an instance of {@link VypisOR }
     * 
     */
    public VypisOR createVypisOR() {
        return new VypisOR();
    }

    /**
     * Create an instance of {@link AngazmaPO }
     * 
     */
    public AngazmaPO createAngazmaPO() {
        return new AngazmaPO();
    }

    /**
     * Create an instance of {@link AngazmaFO }
     * 
     */
    public AngazmaFO createAngazmaFO() {
        return new AngazmaFO();
    }

    /**
     * Create an instance of {@link AngazmaPOFO }
     * 
     */
    public AngazmaPOFO createAngazmaPOFO() {
        return new AngazmaPOFO();
    }

    /**
     * Create an instance of {@link AngazmaPONFO }
     * 
     */
    public AngazmaPONFO createAngazmaPONFO() {
        return new AngazmaPONFO();
    }

    /**
     * Create an instance of {@link OstatniSkutecnosti }
     * 
     */
    public OstatniSkutecnosti createOstatniSkutecnosti() {
        return new OstatniSkutecnosti();
    }

    /**
     * Create an instance of {@link Vklad }
     * 
     */
    public Vklad createVklad() {
        return new Vklad();
    }

    /**
     * Create an instance of {@link Splaceno }
     * 
     */
    public Splaceno createSplaceno() {
        return new Splaceno();
    }

    /**
     * Create an instance of {@link Trvani }
     * 
     */
    public Trvani createTrvani() {
        return new Trvani();
    }

    /**
     * Create an instance of {@link ClenSO }
     * 
     */
    public ClenSO createClenSO() {
        return new ClenSO();
    }

    /**
     * Create an instance of {@link StatutarniOrgan }
     * 
     */
    public StatutarniOrgan createStatutarniOrgan() {
        return new StatutarniOrgan();
    }

    /**
     * Create an instance of {@link Likvidace }
     * 
     */
    public Likvidace createLikvidace() {
        return new Likvidace();
    }

    /**
     * Create an instance of {@link Prokura }
     * 
     */
    public Prokura createProkura() {
        return new Prokura();
    }

    /**
     * Create an instance of {@link ClenDR }
     * 
     */
    public ClenDR createClenDR() {
        return new ClenDR();
    }

    /**
     * Create an instance of {@link DozorciRada }
     * 
     */
    public DozorciRada createDozorciRada() {
        return new DozorciRada();
    }

    /**
     * Create an instance of {@link SpolecniciBezVkladu }
     * 
     */
    public SpolecniciBezVkladu createSpolecniciBezVkladu() {
        return new SpolecniciBezVkladu();
    }

    /**
     * Create an instance of {@link JednotlivyPodil }
     * 
     */
    public JednotlivyPodil createJednotlivyPodil() {
        return new JednotlivyPodil();
    }

    /**
     * Create an instance of {@link SpolecnyPodil }
     * 
     */
    public SpolecnyPodil createSpolecnyPodil() {
        return new SpolecnyPodil();
    }

    /**
     * Create an instance of {@link UvolnenyPodil }
     * 
     */
    public UvolnenyPodil createUvolnenyPodil() {
        return new UvolnenyPodil();
    }

    /**
     * Create an instance of {@link Komanditista }
     * 
     */
    public Komanditista createKomanditista() {
        return new Komanditista();
    }

    /**
     * Create an instance of {@link SpolecniciSVkladem }
     * 
     */
    public SpolecniciSVkladem createSpolecniciSVkladem() {
        return new SpolecniciSVkladem();
    }

    /**
     * Create an instance of {@link Spolecnici }
     * 
     */
    public Spolecnici createSpolecnici() {
        return new Spolecnici();
    }

    /**
     * Create an instance of {@link ZakladateleSP }
     * 
     */
    public ZakladateleSP createZakladateleSP() {
        return new ZakladateleSP();
    }

    /**
     * Create an instance of {@link ZakladateleOPS }
     * 
     */
    public ZakladateleOPS createZakladateleOPS() {
        return new ZakladateleOPS();
    }

    /**
     * Create an instance of {@link ZrizovateleOZ }
     * 
     */
    public ZrizovateleOZ createZrizovateleOZ() {
        return new ZrizovateleOZ();
    }

    /**
     * Create an instance of {@link ZrizovateleNadace }
     * 
     */
    public ZrizovateleNadace createZrizovateleNadace() {
        return new ZrizovateleNadace();
    }

    /**
     * Create an instance of {@link PuvodVzniku }
     * 
     */
    public PuvodVzniku createPuvodVzniku() {
        return new PuvodVzniku();
    }

    /**
     * Create an instance of {@link UdajeKVZ }
     * 
     */
    public UdajeKVZ createUdajeKVZ() {
        return new UdajeKVZ();
    }

    /**
     * Create an instance of {@link Spravce }
     * 
     */
    public Spravce createSpravce() {
        return new Spravce();
    }

    /**
     * Create an instance of {@link Konkurz }
     * 
     */
    public Konkurz createKonkurz() {
        return new Konkurz();
    }

    /**
     * Create an instance of {@link PravniForma }
     * 
     */
    public PravniForma createPravniForma() {
        return new PravniForma();
    }

    /**
     * Create an instance of {@link OdpovedDml }
     * 
     */
    public OdpovedDml createOdpovedDml() {
        return new OdpovedDml();
    }

    /**
     * Create an instance of {@link VypisDML }
     * 
     */
    public VypisDML createVypisDML() {
        return new VypisDML();
    }

    /**
     * Create an instance of {@link ZakladniUdajeDML }
     * 
     */
    public ZakladniUdajeDML createZakladniUdajeDML() {
        return new ZakladniUdajeDML();
    }

    /**
     * Create an instance of {@link OdpovedCns }
     * 
     */
    public OdpovedCns createOdpovedCns() {
        return new OdpovedCns();
    }

    /**
     * Create an instance of {@link VypisCNS }
     * 
     */
    public VypisCNS createVypisCNS() {
        return new VypisCNS();
    }

    /**
     * Create an instance of {@link ZakladniUdajeCNS }
     * 
     */
    public ZakladniUdajeCNS createZakladniUdajeCNS() {
        return new ZakladniUdajeCNS();
    }

    /**
     * Create an instance of {@link Rozhodnuti }
     * 
     */
    public Rozhodnuti createRozhodnuti() {
        return new Rozhodnuti();
    }

    /**
     * Create an instance of {@link AdresaUIR }
     * 
     */
    public AdresaUIR createAdresaUIR() {
        return new AdresaUIR();
    }

    /**
     * Create an instance of {@link AresOdpovedi }
     * 
     */
    public AresOdpovedi createAresOdpovedi() {
        return new AresOdpovedi();
    }

    /**
     * Create an instance of {@link Odpoved }
     * 
     */
    public Odpoved createOdpoved() {
        return new Odpoved();
    }

    /**
     * Create an instance of {@link ChybovaOdpoved }
     * 
     */
    public ChybovaOdpoved createChybovaOdpoved() {
        return new ChybovaOdpoved();
    }

    /**
     * Create an instance of {@link Identifikace }
     * 
     */
    public Identifikace createIdentifikace() {
        return new Identifikace();
    }

    /**
     * Create an instance of {@link Zaznam }
     * 
     */
    public Zaznam createZaznam() {
        return new Zaznam();
    }

    /**
     * Create an instance of {@link Uvod2 }
     * 
     */
    public Uvod2 createUvod2() {
        return new Uvod2();
    }

    /**
     * Create an instance of {@link TypRegistru2 }
     * 
     */
    public TypRegistru2 createTypRegistru2() {
        return new TypRegistru2();
    }

    /**
     * Create an instance of {@link Soud2 }
     * 
     */
    public Soud2 createSoud2() {
        return new Soud2();
    }

    /**
     * Create an instance of {@link TypZmeny2 }
     * 
     */
    public TypZmeny2 createTypZmeny2() {
        return new TypZmeny2();
    }

    /**
     * Create an instance of {@link StavKVZ2 }
     * 
     */
    public StavKVZ2 createStavKVZ2() {
        return new StavKVZ2();
    }

    /**
     * Create an instance of {@link ShodaICO2 }
     * 
     */
    public ShodaICO2 createShodaICO2() {
        return new ShodaICO2();
    }

    /**
     * Create an instance of {@link ShodaRC2 }
     * 
     */
    public ShodaRC2 createShodaRC2() {
        return new ShodaRC2();
    }

    /**
     * Create an instance of {@link ShodaOF2 }
     * 
     */
    public ShodaOF2 createShodaOF2() {
        return new ShodaOF2();
    }

    /**
     * Create an instance of {@link AdresaARES2 }
     * 
     */
    public AdresaARES2 createAdresaARES2() {
        return new AdresaARES2();
    }

    /**
     * Create an instance of {@link VysledekHledani2 }
     * 
     */
    public VysledekHledani2 createVysledekHledani2() {
        return new VysledekHledani2();
    }

    /**
     * Create an instance of {@link PenezniSuma2 }
     * 
     */
    public PenezniSuma2 createPenezniSuma2() {
        return new PenezniSuma2();
    }

    /**
     * Create an instance of {@link FyzickaOsoba2 }
     * 
     */
    public FyzickaOsoba2 createFyzickaOsoba2() {
        return new FyzickaOsoba2();
    }

    /**
     * Create an instance of {@link PravnickaOsoba2 }
     * 
     */
    public PravnickaOsoba2 createPravnickaOsoba2() {
        return new PravnickaOsoba2();
    }

    /**
     * Create an instance of {@link ErrorARES2 }
     * 
     */
    public ErrorARES2 createErrorARES2() {
        return new ErrorARES2();
    }

    /**
     * Create an instance of {@link Chyba2 }
     * 
     */
    public Chyba2 createChyba2() {
        return new Chyba2();
    }

    /**
     * Create an instance of {@link Okec2 }
     * 
     */
    public Okec2 createOkec2() {
        return new Okec2();
    }

    /**
     * Create an instance of {@link KodOkec2 }
     * 
     */
    public KodOkec2 createKodOkec2() {
        return new KodOkec2();
    }

    /**
     * Create an instance of {@link Nace }
     * 
     */
    public Nace createNace() {
        return new Nace();
    }

    /**
     * Create an instance of {@link KodNace }
     * 
     */
    public KodNace createKodNace() {
        return new KodNace();
    }

    /**
     * Create an instance of {@link OdpovedBasic2 }
     * 
     */
    public OdpovedBasic2 createOdpovedBasic2() {
        return new OdpovedBasic2();
    }

    /**
     * Create an instance of {@link VypisBasic2 }
     * 
     */
    public VypisBasic2 createVypisBasic2() {
        return new VypisBasic2();
    }

    /**
     * Create an instance of {@link RegistraceRZP2 }
     * 
     */
    public RegistraceRZP2 createRegistraceRZP2() {
        return new RegistraceRZP2();
    }

    /**
     * Create an instance of {@link AdresaDorucovaci2 }
     * 
     */
    public AdresaDorucovaci2 createAdresaDorucovaci2() {
        return new AdresaDorucovaci2();
    }

    /**
     * Create an instance of {@link StavSubjektuCeu2 }
     * 
     */
    public StavSubjektuCeu2 createStavSubjektuCeu2() {
        return new StavSubjektuCeu2();
    }

    /**
     * Create an instance of {@link KategoriePoctuPracovniku2 }
     * 
     */
    public KategoriePoctuPracovniku2 createKategoriePoctuPracovniku2() {
        return new KategoriePoctuPracovniku2();
    }

    /**
     * Create an instance of {@link InstitucionarniSektor }
     * 
     */
    public InstitucionarniSektor createInstitucionarniSektor() {
        return new InstitucionarniSektor();
    }

    /**
     * Create an instance of {@link Stav2 }
     * 
     */
    public Stav2 createStav2() {
        return new Stav2();
    }

    /**
     * Create an instance of {@link Registrace2 }
     * 
     */
    public Registrace2 createRegistrace2() {
        return new Registrace2();
    }

    /**
     * Create an instance of {@link SpisovaZnacka2 }
     * 
     */
    public SpisovaZnacka2 createSpisovaZnacka2() {
        return new SpisovaZnacka2();
    }

    /**
     * Create an instance of {@link Cinnosti }
     * 
     */
    public Cinnosti createCinnosti() {
        return new Cinnosti();
    }

    /**
     * Create an instance of {@link PredmetyPodnikani2 }
     * 
     */
    public PredmetyPodnikani2 createPredmetyPodnikani2() {
        return new PredmetyPodnikani2();
    }

    /**
     * Create an instance of {@link Texty }
     * 
     */
    public Texty createTexty() {
        return new Texty();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link Ico2 }
     * 
     */
    public Ico2 createIco2() {
        return new Ico2();
    }

    /**
     * Create an instance of {@link ObchodniFirma2 }
     * 
     */
    public ObchodniFirma2 createObchodniFirma2() {
        return new ObchodniFirma2();
    }

    /**
     * Create an instance of {@link CiziNazev }
     * 
     */
    public CiziNazev createCiziNazev() {
        return new CiziNazev();
    }

    /**
     * Create an instance of {@link Dic2 }
     * 
     */
    public Dic2 createDic2() {
        return new Dic2();
    }

    /**
     * Create an instance of {@link VypisRFO2 }
     * 
     */
    public VypisRFO2 createVypisRFO2() {
        return new VypisRFO2();
    }

    /**
     * Create an instance of {@link KrajRFO2 }
     * 
     */
    public KrajRFO2 createKrajRFO2() {
        return new KrajRFO2();
    }

    /**
     * Create an instance of {@link OkresRFO2 }
     * 
     */
    public OkresRFO2 createOkresRFO2() {
        return new OkresRFO2();
    }

    /**
     * Create an instance of {@link ObecRFO2 }
     * 
     */
    public ObecRFO2 createObecRFO2() {
        return new ObecRFO2();
    }

    /**
     * Create an instance of {@link PrazskyObvodRFO2 }
     * 
     */
    public PrazskyObvodRFO2 createPrazskyObvodRFO2() {
        return new PrazskyObvodRFO2();
    }

    /**
     * Create an instance of {@link MestskaCastRFO2 }
     * 
     */
    public MestskaCastRFO2 createMestskaCastRFO2() {
        return new MestskaCastRFO2();
    }

    /**
     * Create an instance of {@link CastObceRFO2 }
     * 
     */
    public CastObceRFO2 createCastObceRFO2() {
        return new CastObceRFO2();
    }

    /**
     * Create an instance of {@link OdpovedOR2 }
     * 
     */
    public OdpovedOR2 createOdpovedOR2() {
        return new OdpovedOR2();
    }

    /**
     * Create an instance of {@link VypisOR2 }
     * 
     */
    public VypisOR2 createVypisOR2() {
        return new VypisOR2();
    }

    /**
     * Create an instance of {@link Angazma }
     * 
     */
    public Angazma createAngazma() {
        return new Angazma();
    }

    /**
     * Create an instance of {@link ZakladniUdajeOR2 }
     * 
     */
    public ZakladniUdajeOR2 createZakladniUdajeOR2() {
        return new ZakladniUdajeOR2();
    }

    /**
     * Create an instance of {@link Udalosti }
     * 
     */
    public Udalosti createUdalosti() {
        return new Udalosti();
    }

    /**
     * Create an instance of {@link Udalost }
     * 
     */
    public Udalost createUdalost() {
        return new Udalost();
    }

    /**
     * Create an instance of {@link OstatniSkutecnosti2 }
     * 
     */
    public OstatniSkutecnosti2 createOstatniSkutecnosti2() {
        return new OstatniSkutecnosti2();
    }

    /**
     * Create an instance of {@link VkladSpolecnika }
     * 
     */
    public VkladSpolecnika createVkladSpolecnika() {
        return new VkladSpolecnika();
    }

    /**
     * Create an instance of {@link Vklad2 }
     * 
     */
    public Vklad2 createVklad2() {
        return new Vklad2();
    }

    /**
     * Create an instance of {@link Splaceno2 }
     * 
     */
    public Splaceno2 createSplaceno2() {
        return new Splaceno2();
    }

    /**
     * Create an instance of {@link Kapital2 }
     * 
     */
    public Kapital2 createKapital2() {
        return new Kapital2();
    }

    /**
     * Create an instance of {@link Jmeni }
     * 
     */
    public Jmeni createJmeni() {
        return new Jmeni();
    }

    /**
     * Create an instance of {@link StatutarniOrgan2 }
     * 
     */
    public StatutarniOrgan2 createStatutarniOrgan2() {
        return new StatutarniOrgan2();
    }

    /**
     * Create an instance of {@link Clen }
     * 
     */
    public Clen createClen() {
        return new Clen();
    }

    /**
     * Create an instance of {@link Sos }
     * 
     */
    public Sos createSos() {
        return new Sos();
    }

    /**
     * Create an instance of {@link Sok }
     * 
     */
    public Sok createSok() {
        return new Sok();
    }

    /**
     * Create an instance of {@link Sop }
     * 
     */
    public Sop createSop() {
        return new Sop();
    }

    /**
     * Create an instance of {@link Szo }
     * 
     */
    public Szo createSzo() {
        return new Szo();
    }

    /**
     * Create an instance of {@link Trvani2 }
     * 
     */
    public Trvani2 createTrvani2() {
        return new Trvani2();
    }

    /**
     * Create an instance of {@link Spolecnik }
     * 
     */
    public Spolecnik createSpolecnik() {
        return new Spolecnik();
    }

    /**
     * Create an instance of {@link cz.stuchlikova.ares.application.stub.Komplementari }
     * 
     */
    public cz.stuchlikova.ares.application.stub.Komplementari createKomplementari() {
        return new cz.stuchlikova.ares.application.stub.Komplementari();
    }

    /**
     * Create an instance of {@link cz.stuchlikova.ares.application.stub.Komanditiste }
     * 
     */
    public cz.stuchlikova.ares.application.stub.Komanditiste createKomanditiste() {
        return new cz.stuchlikova.ares.application.stub.Komanditiste();
    }

    /**
     * Create an instance of {@link ClenoveSdruzeni }
     * 
     */
    public ClenoveSdruzeni createClenoveSdruzeni() {
        return new ClenoveSdruzeni();
    }

    /**
     * Create an instance of {@link Druzstevnici }
     * 
     */
    public Druzstevnici createDruzstevnici() {
        return new Druzstevnici();
    }

    /**
     * Create an instance of {@link Predstavenstvo }
     * 
     */
    public Predstavenstvo createPredstavenstvo() {
        return new Predstavenstvo();
    }

    /**
     * Create an instance of {@link SpravniRada }
     * 
     */
    public SpravniRada createSpravniRada() {
        return new SpravniRada();
    }

    /**
     * Create an instance of {@link Nadace }
     * 
     */
    public Nadace createNadace() {
        return new Nadace();
    }

    /**
     * Create an instance of {@link NadacniFond }
     * 
     */
    public NadacniFond createNadacniFond() {
        return new NadacniFond();
    }

    /**
     * Create an instance of {@link Revizori }
     * 
     */
    public Revizori createRevizori() {
        return new Revizori();
    }

    /**
     * Create an instance of {@link SpolecniciBezVkladu2 }
     * 
     */
    public SpolecniciBezVkladu2 createSpolecniciBezVkladu2() {
        return new SpolecniciBezVkladu2();
    }

    /**
     * Create an instance of {@link SpolecniciSVkladem2 }
     * 
     */
    public SpolecniciSVkladem2 createSpolecniciSVkladem2() {
        return new SpolecniciSVkladem2();
    }

    /**
     * Create an instance of {@link Akcionari }
     * 
     */
    public Akcionari createAkcionari() {
        return new Akcionari();
    }

    /**
     * Create an instance of {@link VedOz }
     * 
     */
    public VedOz createVedOz() {
        return new VedOz();
    }

    /**
     * Create an instance of {@link Likvidace2 }
     * 
     */
    public Likvidace2 createLikvidace2() {
        return new Likvidace2();
    }

    /**
     * Create an instance of {@link Prokura2 }
     * 
     */
    public Prokura2 createProkura2() {
        return new Prokura2();
    }

    /**
     * Create an instance of {@link RediteleOps }
     * 
     */
    public RediteleOps createRediteleOps() {
        return new RediteleOps();
    }

    /**
     * Create an instance of {@link DozorciRada2 }
     * 
     */
    public DozorciRada2 createDozorciRada2() {
        return new DozorciRada2();
    }

    /**
     * Create an instance of {@link KontrolniKomise }
     * 
     */
    public KontrolniKomise createKontrolniKomise() {
        return new KontrolniKomise();
    }

    /**
     * Create an instance of {@link ZakladateleSP2 }
     * 
     */
    public ZakladateleSP2 createZakladateleSP2() {
        return new ZakladateleSP2();
    }

    /**
     * Create an instance of {@link ZakladateleOPS2 }
     * 
     */
    public ZakladateleOPS2 createZakladateleOPS2() {
        return new ZakladateleOPS2();
    }

    /**
     * Create an instance of {@link ZrizovateleOZ2 }
     * 
     */
    public ZrizovateleOZ2 createZrizovateleOZ2() {
        return new ZrizovateleOZ2();
    }

    /**
     * Create an instance of {@link ZrizovatelePR }
     * 
     */
    public ZrizovatelePR createZrizovatelePR() {
        return new ZrizovatelePR();
    }

    /**
     * Create an instance of {@link NastupciZrizovatele }
     * 
     */
    public NastupciZrizovatele createNastupciZrizovatele() {
        return new NastupciZrizovatele();
    }

    /**
     * Create an instance of {@link ZrizovateleNadace2 }
     * 
     */
    public ZrizovateleNadace2 createZrizovateleNadace2() {
        return new ZrizovateleNadace2();
    }

    /**
     * Create an instance of {@link Spravce2 }
     * 
     */
    public Spravce2 createSpravce2() {
        return new Spravce2();
    }

    /**
     * Create an instance of {@link Konkurz2 }
     * 
     */
    public Konkurz2 createKonkurz2() {
        return new Konkurz2();
    }

    /**
     * Create an instance of {@link UdajeKVZ2 }
     * 
     */
    public UdajeKVZ2 createUdajeKVZ2() {
        return new UdajeKVZ2();
    }

    /**
     * Create an instance of {@link TxtKVZ }
     * 
     */
    public TxtKVZ createTxtKVZ() {
        return new TxtKVZ();
    }

    /**
     * Create an instance of {@link PravniForma2 }
     * 
     */
    public PravniForma2 createPravniForma2() {
        return new PravniForma2();
    }

    /**
     * Create an instance of {@link OdpovedRES }
     * 
     */
    public OdpovedRES createOdpovedRES() {
        return new OdpovedRES();
    }

    /**
     * Create an instance of {@link VypisRES }
     * 
     */
    public VypisRES createVypisRES() {
        return new VypisRES();
    }

    /**
     * Create an instance of {@link ZakladniUdajeRES }
     * 
     */
    public ZakladniUdajeRES createZakladniUdajeRES() {
        return new ZakladniUdajeRES();
    }

    /**
     * Create an instance of {@link TypFyzickeOsoby }
     * 
     */
    public TypFyzickeOsoby createTypFyzickeOsoby() {
        return new TypFyzickeOsoby();
    }

    /**
     * Create an instance of {@link StatistickeUdaje }
     * 
     */
    public StatistickeUdaje createStatistickeUdaje() {
        return new StatistickeUdaje();
    }

    /**
     * Create an instance of {@link DoplnujiciPravniFormy }
     * 
     */
    public DoplnujiciPravniFormy createDoplnujiciPravniFormy() {
        return new DoplnujiciPravniFormy();
    }

    /**
     * Create an instance of {@link Zuj }
     * 
     */
    public Zuj createZuj() {
        return new Zuj();
    }

    /**
     * Create an instance of {@link OdpovedRZZ }
     * 
     */
    public OdpovedRZZ createOdpovedRZZ() {
        return new OdpovedRZZ();
    }

    /**
     * Create an instance of {@link VypisRZZ }
     * 
     */
    public VypisRZZ createVypisRZZ() {
        return new VypisRZZ();
    }

    /**
     * Create an instance of {@link ZakladniUdajeRZZ }
     * 
     */
    public ZakladniUdajeRZZ createZakladniUdajeRZZ() {
        return new ZakladniUdajeRZZ();
    }

    /**
     * Create an instance of {@link TypZdravotnickehoZarizeni }
     * 
     */
    public TypZdravotnickehoZarizeni createTypZdravotnickehoZarizeni() {
        return new TypZdravotnickehoZarizeni();
    }

    /**
     * Create an instance of {@link DalsiUdaje }
     * 
     */
    public DalsiUdaje createDalsiUdaje() {
        return new DalsiUdaje();
    }

    /**
     * Create an instance of {@link OdpovedRcns }
     * 
     */
    public OdpovedRcns createOdpovedRcns() {
        return new OdpovedRcns();
    }

    /**
     * Create an instance of {@link VypisRcns }
     * 
     */
    public VypisRcns createVypisRcns() {
        return new VypisRcns();
    }

    /**
     * Create an instance of {@link ZakladniUdajeRCNS }
     * 
     */
    public ZakladniUdajeRCNS createZakladniUdajeRCNS() {
        return new ZakladniUdajeRCNS();
    }

    /**
     * Create an instance of {@link RegistraceRCNS }
     * 
     */
    public RegistraceRCNS createRegistraceRCNS() {
        return new RegistraceRCNS();
    }

    /**
     * Create an instance of {@link Organy }
     * 
     */
    public Organy createOrgany() {
        return new Organy();
    }

    /**
     * Create an instance of {@link OrganPO }
     * 
     */
    public OrganPO createOrganPO() {
        return new OrganPO();
    }

    /**
     * Create an instance of {@link OrganFO }
     * 
     */
    public OrganFO createOrganFO() {
        return new OrganFO();
    }

    /**
     * Create an instance of {@link OsobniUdaje }
     * 
     */
    public OsobniUdaje createOsobniUdaje() {
        return new OsobniUdaje();
    }

    /**
     * Create an instance of {@link StdadrDotaz }
     * 
     */
    public StdadrDotaz createStdadrDotaz() {
        return new StdadrDotaz();
    }

    /**
     * Create an instance of {@link OdpovedStdadr }
     * 
     */
    public OdpovedStdadr createOdpovedStdadr() {
        return new OdpovedStdadr();
    }

    /**
     * Create an instance of {@link StdadrOdpoved }
     * 
     */
    public StdadrOdpoved createStdadrOdpoved() {
        return new StdadrOdpoved();
    }

    /**
     * Create an instance of {@link VysledekDotazu2 }
     * 
     */
    public VysledekDotazu2 createVysledekDotazu2() {
        return new VysledekDotazu2();
    }

    /**
     * Create an instance of {@link SeznamNavracenych2 }
     * 
     */
    public SeznamNavracenych2 createSeznamNavracenych2() {
        return new SeznamNavracenych2();
    }

    /**
     * Create an instance of {@link Slovo2 }
     * 
     */
    public Slovo2 createSlovo2() {
        return new Slovo2();
    }

    /**
     * Create an instance of {@link PrizAdresaARES }
     * 
     */
    public PrizAdresaARES createPrizAdresaARES() {
        return new PrizAdresaARES();
    }

    /**
     * Create an instance of {@link OdpovedRZP2 }
     * 
     */
    public OdpovedRZP2 createOdpovedRZP2() {
        return new OdpovedRZP2();
    }

    /**
     * Create an instance of {@link VypisRZP2 }
     * 
     */
    public VypisRZP2 createVypisRZP2() {
        return new VypisRZP2();
    }

    /**
     * Create an instance of {@link ZakladniUdajeRZP2 }
     * 
     */
    public ZakladniUdajeRZP2 createZakladniUdajeRZP2() {
        return new ZakladniUdajeRZP2();
    }

    /**
     * Create an instance of {@link AdresyRZP }
     * 
     */
    public AdresyRZP createAdresyRZP() {
        return new AdresyRZP();
    }

    /**
     * Create an instance of {@link OsobyRZP }
     * 
     */
    public OsobyRZP createOsobyRZP() {
        return new OsobyRZP();
    }

    /**
     * Create an instance of {@link ZivnostiRZP2 }
     * 
     */
    public ZivnostiRZP2 createZivnostiRZP2() {
        return new ZivnostiRZP2();
    }

    /**
     * Create an instance of {@link Zivnost2 }
     * 
     */
    public Zivnost2 createZivnost2() {
        return new Zivnost2();
    }

    /**
     * Create an instance of {@link UpadkyRZP }
     * 
     */
    public UpadkyRZP createUpadkyRZP() {
        return new UpadkyRZP();
    }

    /**
     * Create an instance of {@link Upadek }
     * 
     */
    public Upadek createUpadek() {
        return new Upadek();
    }

    /**
     * Create an instance of {@link OboryCinnosti }
     * 
     */
    public OboryCinnosti createOboryCinnosti() {
        return new OboryCinnosti();
    }

    /**
     * Create an instance of {@link OborCinnosti }
     * 
     */
    public OborCinnosti createOborCinnosti() {
        return new OborCinnosti();
    }

    /**
     * Create an instance of {@link OsobaRZP }
     * 
     */
    public OsobaRZP createOsobaRZP() {
        return new OsobaRZP();
    }

    /**
     * Create an instance of {@link ProvozovnyRZP2 }
     * 
     */
    public ProvozovnyRZP2 createProvozovnyRZP2() {
        return new ProvozovnyRZP2();
    }

    /**
     * Create an instance of {@link Provozovna2 }
     * 
     */
    public Provozovna2 createProvozovna2() {
        return new Provozovna2();
    }

    /**
     * Create an instance of {@link ZivnostenskyUrad2 }
     * 
     */
    public ZivnostenskyUrad2 createZivnostenskyUrad2() {
        return new ZivnostenskyUrad2();
    }

    /**
     * Create an instance of {@link FinancniUrad2 }
     * 
     */
    public FinancniUrad2 createFinancniUrad2() {
        return new FinancniUrad2();
    }

    /**
     * Create an instance of {@link OdpovedEs }
     * 
     */
    public OdpovedEs createOdpovedEs() {
        return new OdpovedEs();
    }

    /**
     * Create an instance of {@link VypisStrankyPrehledu }
     * 
     */
    public VypisStrankyPrehledu createVypisStrankyPrehledu() {
        return new VypisStrankyPrehledu();
    }

    /**
     * Create an instance of {@link VypisSubjektu }
     * 
     */
    public VypisSubjektu createVypisSubjektu() {
        return new VypisSubjektu();
    }

    /**
     * Create an instance of {@link HelpARES }
     * 
     */
    public HelpARES createHelpARES() {
        return new HelpARES();
    }

    /**
     * Create an instance of {@link OdpovedFo }
     * 
     */
    public OdpovedFo createOdpovedFo() {
        return new OdpovedFo();
    }

    /**
     * Create an instance of {@link VypisStrankyFo }
     * 
     */
    public VypisStrankyFo createVypisStrankyFo() {
        return new VypisStrankyFo();
    }

    /**
     * Create an instance of {@link VypisOsoby }
     * 
     */
    public VypisOsoby createVypisOsoby() {
        return new VypisOsoby();
    }

    /**
     * Create an instance of {@link OdpovedOss }
     * 
     */
    public OdpovedOss createOdpovedOss() {
        return new OdpovedOss();
    }

    /**
     * Create an instance of {@link VypisOss }
     * 
     */
    public VypisOss createVypisOss() {
        return new VypisOss();
    }

    /**
     * Create an instance of {@link ParentOss }
     * 
     */
    public ParentOss createParentOss() {
        return new ParentOss();
    }

    /**
     * Create an instance of {@link OrgSlozkyOss }
     * 
     */
    public OrgSlozkyOss createOrgSlozkyOss() {
        return new OrgSlozkyOss();
    }

    /**
     * Create an instance of {@link OrgSlozkaOss }
     * 
     */
    public OrgSlozkaOss createOrgSlozkaOss() {
        return new OrgSlozkaOss();
    }

    /**
     * Create an instance of {@link NazevOss }
     * 
     */
    public NazevOss createNazevOss() {
        return new NazevOss();
    }

    /**
     * Create an instance of {@link TypHnuti }
     * 
     */
    public TypHnuti createTypHnuti() {
        return new TypHnuti();
    }

    /**
     * Create an instance of {@link OdpovedCeuDetail }
     * 
     */
    public OdpovedCeuDetail createOdpovedCeuDetail() {
        return new OdpovedCeuDetail();
    }

    /**
     * Create an instance of {@link VypisCeuDetail }
     * 
     */
    public VypisCeuDetail createVypisCeuDetail() {
        return new VypisCeuDetail();
    }

    /**
     * Create an instance of {@link JednotliveUkony }
     * 
     */
    public JednotliveUkony createJednotliveUkony() {
        return new JednotliveUkony();
    }

    /**
     * Create an instance of {@link DetailniSpisovaZnacka }
     * 
     */
    public DetailniSpisovaZnacka createDetailniSpisovaZnacka() {
        return new DetailniSpisovaZnacka();
    }

    /**
     * Create an instance of {@link OdpovedSzr }
     * 
     */
    public OdpovedSzr createOdpovedSzr() {
        return new OdpovedSzr();
    }

    /**
     * Create an instance of {@link OsobaSzr }
     * 
     */
    public OsobaSzr createOsobaSzr() {
        return new OsobaSzr();
    }

    /**
     * Create an instance of {@link PodnikatelEzp }
     * 
     */
    public PodnikatelEzp createPodnikatelEzp() {
        return new PodnikatelEzp();
    }

    /**
     * Create an instance of {@link AngazmaSzr }
     * 
     */
    public AngazmaSzr createAngazmaSzr() {
        return new AngazmaSzr();
    }

    /**
     * Create an instance of {@link SubjektSzr }
     * 
     */
    public SubjektSzr createSubjektSzr() {
        return new SubjektSzr();
    }

    /**
     * Create an instance of {@link KontaktySzr }
     * 
     */
    public KontaktySzr createKontaktySzr() {
        return new KontaktySzr();
    }

    /**
     * Create an instance of {@link ProvozovnySzr }
     * 
     */
    public ProvozovnySzr createProvozovnySzr() {
        return new ProvozovnySzr();
    }

    /**
     * Create an instance of {@link ExidsSzr }
     * 
     */
    public ExidsSzr createExidsSzr() {
        return new ExidsSzr();
    }

    /**
     * Create an instance of {@link RegistrySzr }
     * 
     */
    public RegistrySzr createRegistrySzr() {
        return new RegistrySzr();
    }

    /**
     * Create an instance of {@link KontaktSzr }
     * 
     */
    public KontaktSzr createKontaktSzr() {
        return new KontaktSzr();
    }

    /**
     * Create an instance of {@link AdresySzr }
     * 
     */
    public AdresySzr createAdresySzr() {
        return new AdresySzr();
    }

    /**
     * Create an instance of {@link AdresaSzr }
     * 
     */
    public AdresaSzr createAdresaSzr() {
        return new AdresaSzr();
    }

    /**
     * Create an instance of {@link AdresaEzp }
     * 
     */
    public AdresaEzp createAdresaEzp() {
        return new AdresaEzp();
    }

    /**
     * Create an instance of {@link ProvozovnaSzr }
     * 
     */
    public ProvozovnaSzr createProvozovnaSzr() {
        return new ProvozovnaSzr();
    }

    /**
     * Create an instance of {@link Exid }
     * 
     */
    public Exid createExid() {
        return new Exid();
    }

    /**
     * Create an instance of {@link RegistrSzr }
     * 
     */
    public RegistrSzr createRegistrSzr() {
        return new RegistrSzr();
    }

    /**
     * Create an instance of {@link RegistrEzp }
     * 
     */
    public RegistrEzp createRegistrEzp() {
        return new RegistrEzp();
    }

    /**
     * Create an instance of {@link OboryRvp }
     * 
     */
    public OboryRvp createOboryRvp() {
        return new OboryRvp();
    }

    /**
     * Create an instance of {@link OborRvp }
     * 
     */
    public OborRvp createOborRvp() {
        return new OborRvp();
    }

    /**
     * Create an instance of {@link UkonyEzp }
     * 
     */
    public UkonyEzp createUkonyEzp() {
        return new UkonyEzp();
    }

    /**
     * Create an instance of {@link UkonEzp }
     * 
     */
    public UkonEzp createUkonEzp() {
        return new UkonEzp();
    }

    /**
     * Create an instance of {@link OdpovedZm }
     * 
     */
    public OdpovedZm createOdpovedZm() {
        return new OdpovedZm();
    }

    /**
     * Create an instance of {@link Zadani }
     * 
     */
    public Zadani createZadani() {
        return new Zadani();
    }

    /**
     * Create an instance of {@link SeznamSubjektu }
     * 
     */
    public SeznamSubjektu createSeznamSubjektu() {
        return new SeznamSubjektu();
    }

    /**
     * Create an instance of {@link PriznakZmeny }
     * 
     */
    public PriznakZmeny createPriznakZmeny() {
        return new PriznakZmeny();
    }

    /**
     * Create an instance of {@link CisloDavky }
     * 
     */
    public CisloDavky createCisloDavky() {
        return new CisloDavky();
    }

    /**
     * Create an instance of {@link OdpovedRpsh }
     * 
     */
    public OdpovedRpsh createOdpovedRpsh() {
        return new OdpovedRpsh();
    }

    /**
     * Create an instance of {@link SubjektRpsh }
     * 
     */
    public SubjektRpsh createSubjektRpsh() {
        return new SubjektRpsh();
    }

    /**
     * Create an instance of {@link NazvyRpsh }
     * 
     */
    public NazvyRpsh createNazvyRpsh() {
        return new NazvyRpsh();
    }

    /**
     * Create an instance of {@link OsobyRpsh }
     * 
     */
    public OsobyRpsh createOsobyRpsh() {
        return new OsobyRpsh();
    }

    /**
     * Create an instance of {@link AdresyRpsh }
     * 
     */
    public AdresyRpsh createAdresyRpsh() {
        return new AdresyRpsh();
    }

    /**
     * Create an instance of {@link StatutOrganyRpsh }
     * 
     */
    public StatutOrganyRpsh createStatutOrganyRpsh() {
        return new StatutOrganyRpsh();
    }

    /**
     * Create an instance of {@link ZmenyStanovRpsh }
     * 
     */
    public ZmenyStanovRpsh createZmenyStanovRpsh() {
        return new ZmenyStanovRpsh();
    }

    /**
     * Create an instance of {@link StavySubjRpsh }
     * 
     */
    public StavySubjRpsh createStavySubjRpsh() {
        return new StavySubjRpsh();
    }

    /**
     * Create an instance of {@link NazevRpsh }
     * 
     */
    public NazevRpsh createNazevRpsh() {
        return new NazevRpsh();
    }

    /**
     * Create an instance of {@link OsobaRpsh }
     * 
     */
    public OsobaRpsh createOsobaRpsh() {
        return new OsobaRpsh();
    }

    /**
     * Create an instance of {@link AdresaRpsh }
     * 
     */
    public AdresaRpsh createAdresaRpsh() {
        return new AdresaRpsh();
    }

    /**
     * Create an instance of {@link StatutOrganRpsh }
     * 
     */
    public StatutOrganRpsh createStatutOrganRpsh() {
        return new StatutOrganRpsh();
    }

    /**
     * Create an instance of {@link ZmenaStanovRpsh }
     * 
     */
    public ZmenaStanovRpsh createZmenaStanovRpsh() {
        return new ZmenaStanovRpsh();
    }

    /**
     * Create an instance of {@link StavSubjRpsh }
     * 
     */
    public StavSubjRpsh createStavSubjRpsh() {
        return new StavSubjRpsh();
    }

    /**
     * Create an instance of {@link OdpovedIR }
     * 
     */
    public OdpovedIR createOdpovedIR() {
        return new OdpovedIR();
    }

    /**
     * Create an instance of {@link VypisIR }
     * 
     */
    public VypisIR createVypisIR() {
        return new VypisIR();
    }

    /**
     * Create an instance of {@link ZakladniUdajeIR }
     * 
     */
    public ZakladniUdajeIR createZakladniUdajeIR() {
        return new ZakladniUdajeIR();
    }

    /**
     * Create an instance of {@link SpisovaZnackaIR }
     * 
     */
    public SpisovaZnackaIR createSpisovaZnackaIR() {
        return new SpisovaZnackaIR();
    }

    /**
     * Create an instance of {@link InsolvencniSpravci }
     * 
     */
    public InsolvencniSpravci createInsolvencniSpravci() {
        return new InsolvencniSpravci();
    }

    /**
     * Create an instance of {@link ISpravce }
     * 
     */
    public ISpravce createISpravce() {
        return new ISpravce();
    }

    /**
     * Create an instance of {@link OsobaIR }
     * 
     */
    public OsobaIR createOsobaIR() {
        return new OsobaIR();
    }

    /**
     * Create an instance of {@link AdresyIR }
     * 
     */
    public AdresyIR createAdresyIR() {
        return new AdresyIR();
    }

    /**
     * Create an instance of {@link AdresaIR }
     * 
     */
    public AdresaIR createAdresaIR() {
        return new AdresaIR();
    }

    /**
     * Create an instance of {@link HistorieIR }
     * 
     */
    public HistorieIR createHistorieIR() {
        return new HistorieIR();
    }

    /**
     * Create an instance of {@link VetyIR }
     * 
     */
    public VetyIR createVetyIR() {
        return new VetyIR();
    }

    /**
     * Create an instance of {@link VetaIR }
     * 
     */
    public VetaIR createVetaIR() {
        return new VetaIR();
    }

    /**
     * Create an instance of {@link OdpovedSko }
     * 
     */
    public OdpovedSko createOdpovedSko() {
        return new OdpovedSko();
    }

    /**
     * Create an instance of {@link SubjektSko }
     * 
     */
    public SubjektSko createSubjektSko() {
        return new SubjektSko();
    }

    /**
     * Create an instance of {@link ZakladniUdajeEksSko }
     * 
     */
    public ZakladniUdajeEksSko createZakladniUdajeEksSko() {
        return new ZakladniUdajeEksSko();
    }

    /**
     * Create an instance of {@link AngazmaSko }
     * 
     */
    public AngazmaSko createAngazmaSko() {
        return new AngazmaSko();
    }

    /**
     * Create an instance of {@link SoucastiSko }
     * 
     */
    public SoucastiSko createSoucastiSko() {
        return new SoucastiSko();
    }

    /**
     * Create an instance of {@link AngazSko }
     * 
     */
    public AngazSko createAngazSko() {
        return new AngazSko();
    }

    /**
     * Create an instance of {@link FunkceSko }
     * 
     */
    public FunkceSko createFunkceSko() {
        return new FunkceSko();
    }

    /**
     * Create an instance of {@link SoucastSko }
     * 
     */
    public SoucastSko createSoucastSko() {
        return new SoucastSko();
    }

    /**
     * Create an instance of {@link TypSoucastiSko }
     * 
     */
    public TypSoucastiSko createTypSoucastiSko() {
        return new TypSoucastiSko();
    }

    /**
     * Create an instance of {@link PravnickaOsobaSko }
     * 
     */
    public PravnickaOsobaSko createPravnickaOsobaSko() {
        return new PravnickaOsobaSko();
    }

    /**
     * Create an instance of {@link FyzickaOsobaSko }
     * 
     */
    public FyzickaOsobaSko createFyzickaOsobaSko() {
        return new FyzickaOsobaSko();
    }

    /**
     * Create an instance of {@link OsobniUdajeSko }
     * 
     */
    public OsobniUdajeSko createOsobniUdajeSko() {
        return new OsobniUdajeSko();
    }

    /**
     * Create an instance of {@link ZakladniUdajeRosDetail }
     * 
     */
    public ZakladniUdajeRosDetail createZakladniUdajeRosDetail() {
        return new ZakladniUdajeRosDetail();
    }

    /**
     * Create an instance of {@link PravniStavRos }
     * 
     */
    public PravniStavRos createPravniStavRos() {
        return new PravniStavRos();
    }

    /**
     * Create an instance of {@link OdpovedRos }
     * 
     */
    public OdpovedRos createOdpovedRos() {
        return new OdpovedRos();
    }

    /**
     * Create an instance of {@link VypisROS }
     * 
     */
    public VypisROS createVypisROS() {
        return new VypisROS();
    }

    /**
     * Create an instance of {@link ZakladniUdajeRos }
     * 
     */
    public ZakladniUdajeRos createZakladniUdajeRos() {
        return new ZakladniUdajeRos();
    }

    /**
     * Create an instance of {@link DatumRos }
     * 
     */
    public DatumRos createDatumRos() {
        return new DatumRos();
    }

    /**
     * Create an instance of {@link PfRos }
     * 
     */
    public PfRos createPfRos() {
        return new PfRos();
    }

    /**
     * Create an instance of {@link PsRos }
     * 
     */
    public PsRos createPsRos() {
        return new PsRos();
    }

    /**
     * Create an instance of {@link DatoveSchranky }
     * 
     */
    public DatoveSchranky createDatoveSchranky() {
        return new DatoveSchranky();
    }

    /**
     * Create an instance of {@link DatovaSchranka }
     * 
     */
    public DatovaSchranka createDatovaSchranka() {
        return new DatovaSchranka();
    }

    /**
     * Create an instance of {@link PodnikatelRos }
     * 
     */
    public PodnikatelRos createPodnikatelRos() {
        return new PodnikatelRos();
    }

    /**
     * Create an instance of {@link AgendyRos }
     * 
     */
    public AgendyRos createAgendyRos() {
        return new AgendyRos();
    }

    /**
     * Create an instance of {@link AgendaRos }
     * 
     */
    public AgendaRos createAgendaRos() {
        return new AgendaRos();
    }

    /**
     * Create an instance of {@link AgendaKodNazev }
     * 
     */
    public AgendaKodNazev createAgendaKodNazev() {
        return new AgendaKodNazev();
    }

    /**
     * Create an instance of {@link KodNazevOvm }
     * 
     */
    public KodNazevOvm createKodNazevOvm() {
        return new KodNazevOvm();
    }

    /**
     * Create an instance of {@link OfRos }
     * 
     */
    public OfRos createOfRos() {
        return new OfRos();
    }

    /**
     * Create an instance of {@link SidloRos }
     * 
     */
    public SidloRos createSidloRos() {
        return new SidloRos();
    }

    /**
     * Create an instance of {@link StatutariRos }
     * 
     */
    public StatutariRos createStatutariRos() {
        return new StatutariRos();
    }

    /**
     * Create an instance of {@link StatutarRos }
     * 
     */
    public StatutarRos createStatutarRos() {
        return new StatutarRos();
    }

    /**
     * Create an instance of {@link ProvozovnyRos }
     * 
     */
    public ProvozovnyRos createProvozovnyRos() {
        return new ProvozovnyRos();
    }

    /**
     * Create an instance of {@link ProvozovnaRos }
     * 
     */
    public ProvozovnaRos createProvozovnaRos() {
        return new ProvozovnaRos();
    }

    /**
     * Create an instance of {@link KonkurzyVyrovnani2 .Ukon }
     * 
     */
    public KonkurzyVyrovnani2 .Ukon createKonkurzyVyrovnani2Ukon() {
        return new KonkurzyVyrovnani2 .Ukon();
    }

    /**
     * Create an instance of {@link OdstepneZavody2 .OdstepnyZavod }
     * 
     */
    public OdstepneZavody2 .OdstepnyZavod createOdstepneZavody2OdstepnyZavod() {
        return new OdstepneZavody2 .OdstepnyZavod();
    }

    /**
     * Create an instance of {@link cz.stuchlikova.ares.application.stub.Akcie.Emise }
     * 
     */
    public cz.stuchlikova.ares.application.stub.Akcie.Emise createAkcieEmise() {
        return new cz.stuchlikova.ares.application.stub.Akcie.Emise();
    }

    /**
     * Create an instance of {@link XsltErrorList.Error }
     * 
     */
    public XsltErrorList.Error createXsltErrorListError() {
        return new XsltErrorList.Error();
    }

    /**
     * Create an instance of {@link KonkurzyVyrovnani.Ukon }
     * 
     */
    public KonkurzyVyrovnani.Ukon createKonkurzyVyrovnaniUkon() {
        return new KonkurzyVyrovnani.Ukon();
    }

    /**
     * Create an instance of {@link OdstepneZavody.OdstepnyZavod.PredmetPodnikani }
     * 
     */
    public OdstepneZavody.OdstepnyZavod.PredmetPodnikani createOdstepneZavodyOdstepnyZavodPredmetPodnikani() {
        return new OdstepneZavody.OdstepnyZavod.PredmetPodnikani();
    }

    /**
     * Create an instance of {@link KomanditniSpolecnici.Komplementari }
     * 
     */
    public KomanditniSpolecnici.Komplementari createKomanditniSpolecniciKomplementari() {
        return new KomanditniSpolecnici.Komplementari();
    }

    /**
     * Create an instance of {@link KomanditniSpolecnici.Komanditiste }
     * 
     */
    public KomanditniSpolecnici.Komanditiste createKomanditniSpolecniciKomanditiste() {
        return new KomanditniSpolecnici.Komanditiste();
    }

    /**
     * Create an instance of {@link ClenskeVklady.ZakladniCV }
     * 
     */
    public ClenskeVklady.ZakladniCV createClenskeVkladyZakladniCV() {
        return new ClenskeVklady.ZakladniCV();
    }

    /**
     * Create an instance of {@link ClenskeVklady.JednotlivyCV }
     * 
     */
    public ClenskeVklady.JednotlivyCV createClenskeVkladyJednotlivyCV() {
        return new ClenskeVklady.JednotlivyCV();
    }

    /**
     * Create an instance of {@link Kapital.VycetNadacnihoMajetku }
     * 
     */
    public Kapital.VycetNadacnihoMajetku createKapitalVycetNadacnihoMajetku() {
        return new Kapital.VycetNadacnihoMajetku();
    }

    /**
     * Create an instance of {@link Kapital.Akcie.Emise }
     * 
     */
    public Kapital.Akcie.Emise createKapitalAkcieEmise() {
        return new Kapital.Akcie.Emise();
    }

    /**
     * Create an instance of {@link ZakladniUdajeOR.Historie.Veta }
     * 
     */
    public ZakladniUdajeOR.Historie.Veta createZakladniUdajeORHistorieVeta() {
        return new ZakladniUdajeOR.Historie.Veta();
    }

    /**
     * Create an instance of {@link Cinnost.DruhOPS }
     * 
     */
    public Cinnost.DruhOPS createCinnostDruhOPS() {
        return new Cinnost.DruhOPS();
    }

    /**
     * Create an instance of {@link Cinnost.PredmetCinnosti }
     * 
     */
    public Cinnost.PredmetCinnosti createCinnostPredmetCinnosti() {
        return new Cinnost.PredmetCinnosti();
    }

    /**
     * Create an instance of {@link Cinnost.DoplnkovaCinnost }
     * 
     */
    public Cinnost.DoplnkovaCinnost createCinnostDoplnkovaCinnost() {
        return new Cinnost.DoplnkovaCinnost();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XsltErrorList }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XsltErrorList }{@code >}
     */
    @XmlElementDecl(namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1", name = "Error_list")
    public JAXBElement<XsltErrorList> createErrorList(XsltErrorList value) {
        return new JAXBElement<XsltErrorList>(_ErrorList_QNAME, XsltErrorList.class, null, value);
    }

}
