//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.19 at 09:56:20 AM CEST 
//


package cz.stuchlikova.ares.application.stub.standard;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for jednotlivy_podil complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jednotlivy_podil"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Spolecnik_s_vkladem" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}angazma_PO_n_FO" minOccurs="0"/&gt;
 *         &lt;element name="Vklad" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}vklad" minOccurs="0"/&gt;
 *         &lt;element name="Splaceno" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}splaceno" minOccurs="0"/&gt;
 *         &lt;element name="Obchodni_podil" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}popis" minOccurs="0"/&gt;
 *         &lt;element name="Zastavni_pravo" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}text" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "jednotlivy_podil", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1", propOrder = {
    "spolecnikSVkladem",
    "vklad",
    "splaceno",
    "obchodniPodil",
    "zastavniPravo"
})
public class JednotlivyPodil {

    @XmlElement(name = "Spolecnik_s_vkladem")
    protected AngazmaPONFO spolecnikSVkladem;
    @XmlElement(name = "Vklad")
    protected Vklad vklad;
    @XmlElement(name = "Splaceno")
    protected Splaceno splaceno;
    @XmlElement(name = "Obchodni_podil")
    protected String obchodniPodil;
    @XmlElement(name = "Zastavni_pravo")
    protected String zastavniPravo;

    /**
     * Gets the value of the spolecnikSVkladem property.
     * 
     * @return
     *     possible object is
     *     {@link AngazmaPONFO }
     *     
     */
    public AngazmaPONFO getSpolecnikSVkladem() {
        return spolecnikSVkladem;
    }

    /**
     * Sets the value of the spolecnikSVkladem property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngazmaPONFO }
     *     
     */
    public void setSpolecnikSVkladem(AngazmaPONFO value) {
        this.spolecnikSVkladem = value;
    }

    /**
     * Gets the value of the vklad property.
     * 
     * @return
     *     possible object is
     *     {@link Vklad }
     *     
     */
    public Vklad getVklad() {
        return vklad;
    }

    /**
     * Sets the value of the vklad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vklad }
     *     
     */
    public void setVklad(Vklad value) {
        this.vklad = value;
    }

    /**
     * Gets the value of the splaceno property.
     * 
     * @return
     *     possible object is
     *     {@link Splaceno }
     *     
     */
    public Splaceno getSplaceno() {
        return splaceno;
    }

    /**
     * Sets the value of the splaceno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Splaceno }
     *     
     */
    public void setSplaceno(Splaceno value) {
        this.splaceno = value;
    }

    /**
     * Gets the value of the obchodniPodil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObchodniPodil() {
        return obchodniPodil;
    }

    /**
     * Sets the value of the obchodniPodil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObchodniPodil(String value) {
        this.obchodniPodil = value;
    }

    /**
     * Gets the value of the zastavniPravo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZastavniPravo() {
        return zastavniPravo;
    }

    /**
     * Sets the value of the zastavniPravo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZastavniPravo(String value) {
        this.zastavniPravo = value;
    }

}
