//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.24 at 03:40:11 PM CET 
//


package cz.stuchlikova.ares.standard.stub;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ares_dotaz_typ.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ares_dotaz_typ"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Standard"/&gt;
 *     &lt;enumeration value="Seznam_Reg"/&gt;
 *     &lt;enumeration value="Vypis_OR"/&gt;
 *     &lt;enumeration value="Vypis_RZP"/&gt;
 *     &lt;enumeration value="Vypis_RES"/&gt;
 *     &lt;enumeration value="Vypis_RZZ"/&gt;
 *     &lt;enumeration value="Basic"/&gt;
 *     &lt;enumeration value="Vypis_DML"/&gt;
 *     &lt;enumeration value="Vypis_CNS"/&gt;
 *     &lt;enumeration value="Vypis_OSS"/&gt;
 *     &lt;enumeration value="Vypis_POZ"/&gt;
 *     &lt;enumeration value="Stdadr"/&gt;
 *     &lt;enumeration value="zl"/&gt;
 *     &lt;enumeration value="es"/&gt;
 *     &lt;enumeration value="su"/&gt;
 *     &lt;enumeration value="fo"/&gt;
 *     &lt;enumeration value="ceu"/&gt;
 *     &lt;enumeration value="zm"/&gt;
 *     &lt;enumeration value="szr"/&gt;
 *     &lt;enumeration value="Vypis_OFF"/&gt;
 *     &lt;enumeration value="Vypis_PSH"/&gt;
 *     &lt;enumeration value="Vypis_IR"/&gt;
 *     &lt;enumeration value="Vypis_SKO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ares_dotaz_typ", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1")
@XmlEnum
public enum AresDotazTyp {

    @XmlEnumValue("Standard")
    STANDARD("Standard"),
    @XmlEnumValue("Seznam_Reg")
    SEZNAM_REG("Seznam_Reg"),
    @XmlEnumValue("Vypis_OR")
    VYPIS_OR("Vypis_OR"),
    @XmlEnumValue("Vypis_RZP")
    VYPIS_RZP("Vypis_RZP"),
    @XmlEnumValue("Vypis_RES")
    VYPIS_RES("Vypis_RES"),
    @XmlEnumValue("Vypis_RZZ")
    VYPIS_RZZ("Vypis_RZZ"),
    @XmlEnumValue("Basic")
    BASIC("Basic"),
    @XmlEnumValue("Vypis_DML")
    VYPIS_DML("Vypis_DML"),
    @XmlEnumValue("Vypis_CNS")
    VYPIS_CNS("Vypis_CNS"),
    @XmlEnumValue("Vypis_OSS")
    VYPIS_OSS("Vypis_OSS"),
    @XmlEnumValue("Vypis_POZ")
    VYPIS_POZ("Vypis_POZ"),
    @XmlEnumValue("Stdadr")
    STDADR("Stdadr"),
    @XmlEnumValue("zl")
    ZL("zl"),
    @XmlEnumValue("es")
    ES("es"),
    @XmlEnumValue("su")
    SU("su"),
    @XmlEnumValue("fo")
    FO("fo"),
    @XmlEnumValue("ceu")
    CEU("ceu"),
    @XmlEnumValue("zm")
    ZM("zm"),
    @XmlEnumValue("szr")
    SZR("szr"),
    @XmlEnumValue("Vypis_OFF")
    VYPIS_OFF("Vypis_OFF"),
    @XmlEnumValue("Vypis_PSH")
    VYPIS_PSH("Vypis_PSH"),
    @XmlEnumValue("Vypis_IR")
    VYPIS_IR("Vypis_IR"),
    @XmlEnumValue("Vypis_SKO")
    VYPIS_SKO("Vypis_SKO");
    private final String value;

    AresDotazTyp(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AresDotazTyp fromValue(String v) {
        for (AresDotazTyp c: AresDotazTyp.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
