//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.29 at 07:54:38 PM CEST 
//


package cz.stuchlikova.ares.standard.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Evidenční číslo živnosti (vz_zivnosti.ec_k_zu a ec_idl)
 * 
 * <p>Java class for evidencni_cislo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="evidencni_cislo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Kod_ZU" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Kod_listu" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "evidencni_cislo", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1", propOrder = {
    "kodZU",
    "kodListu"
})
public class EvidencniCislo {

    @XmlElement(name = "Kod_ZU")
    protected int kodZU;
    @XmlElement(name = "Kod_listu")
    protected int kodListu;

    /**
     * Gets the value of the kodZU property.
     * 
     */
    public int getKodZU() {
        return kodZU;
    }

    /**
     * Sets the value of the kodZU property.
     * 
     */
    public void setKodZU(int value) {
        this.kodZU = value;
    }

    /**
     * Gets the value of the kodListu property.
     * 
     */
    public int getKodListu() {
        return kodListu;
    }

    /**
     * Sets the value of the kodListu property.
     * 
     */
    public void setKodListu(int value) {
        this.kodListu = value;
    }

}
