//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.10 at 07:21:26 PM CET 
//


package cz.stuchlikova.ares.standard.stub;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * informace o základním jmění subjektu
 * 
 * <p>Java class for kapital complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="kapital"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Typ_jmeni" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}typ_jmeni"/&gt;
 *         &lt;element name="Vklad" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}vklad" minOccurs="0"/&gt;
 *         &lt;element name="Splaceno" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}splaceno" minOccurs="0"/&gt;
 *         &lt;element name="Text" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}text" minOccurs="0"/&gt;
 *         &lt;element name="Akcie" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Emise" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Druh_akcie" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}druh_akcie" minOccurs="0"/&gt;
 *                             &lt;element name="Hodnota" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                             &lt;element name="Pocet" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *                             &lt;element name="Text" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}text" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Vycet_nadacniho_majetku" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Text" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}text" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kapital", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1", propOrder = {
    "typJmeni",
    "vklad",
    "splaceno",
    "text",
    "akcie",
    "vycetNadacnihoMajetku"
})
public class Kapital {

    @XmlElement(name = "Typ_jmeni", required = true)
    @XmlSchemaType(name = "string")
    protected TypJmeni typJmeni;
    @XmlElement(name = "Vklad")
    protected Vklad vklad;
    @XmlElement(name = "Splaceno")
    protected Splaceno splaceno;
    @XmlElement(name = "Text")
    protected String text;
    @XmlElement(name = "Akcie")
    protected Kapital.Akcie akcie;
    @XmlElement(name = "Vycet_nadacniho_majetku")
    protected Kapital.VycetNadacnihoMajetku vycetNadacnihoMajetku;

    /**
     * Gets the value of the typJmeni property.
     * 
     * @return
     *     possible object is
     *     {@link TypJmeni }
     *     
     */
    public TypJmeni getTypJmeni() {
        return typJmeni;
    }

    /**
     * Sets the value of the typJmeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypJmeni }
     *     
     */
    public void setTypJmeni(TypJmeni value) {
        this.typJmeni = value;
    }

    /**
     * Gets the value of the vklad property.
     * 
     * @return
     *     possible object is
     *     {@link Vklad }
     *     
     */
    public Vklad getVklad() {
        return vklad;
    }

    /**
     * Sets the value of the vklad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vklad }
     *     
     */
    public void setVklad(Vklad value) {
        this.vklad = value;
    }

    /**
     * Gets the value of the splaceno property.
     * 
     * @return
     *     possible object is
     *     {@link Splaceno }
     *     
     */
    public Splaceno getSplaceno() {
        return splaceno;
    }

    /**
     * Sets the value of the splaceno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Splaceno }
     *     
     */
    public void setSplaceno(Splaceno value) {
        this.splaceno = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the akcie property.
     * 
     * @return
     *     possible object is
     *     {@link Kapital.Akcie }
     *     
     */
    public Kapital.Akcie getAkcie() {
        return akcie;
    }

    /**
     * Sets the value of the akcie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kapital.Akcie }
     *     
     */
    public void setAkcie(Kapital.Akcie value) {
        this.akcie = value;
    }

    /**
     * Gets the value of the vycetNadacnihoMajetku property.
     * 
     * @return
     *     possible object is
     *     {@link Kapital.VycetNadacnihoMajetku }
     *     
     */
    public Kapital.VycetNadacnihoMajetku getVycetNadacnihoMajetku() {
        return vycetNadacnihoMajetku;
    }

    /**
     * Sets the value of the vycetNadacnihoMajetku property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kapital.VycetNadacnihoMajetku }
     *     
     */
    public void setVycetNadacnihoMajetku(Kapital.VycetNadacnihoMajetku value) {
        this.vycetNadacnihoMajetku = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Emise" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Druh_akcie" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}druh_akcie" minOccurs="0"/&gt;
     *                   &lt;element name="Hodnota" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *                   &lt;element name="Pocet" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
     *                   &lt;element name="Text" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}text" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "emise"
    })
    public static class Akcie {

        @XmlElement(name = "Emise", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1", required = true)
        protected List<Kapital.Akcie.Emise> emise;

        /**
         * Gets the value of the emise property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the emise property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEmise().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Kapital.Akcie.Emise }
         * 
         * 
         */
        public List<Kapital.Akcie.Emise> getEmise() {
            if (emise == null) {
                emise = new ArrayList<Kapital.Akcie.Emise>();
            }
            return this.emise;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Druh_akcie" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}druh_akcie" minOccurs="0"/&gt;
         *         &lt;element name="Hodnota" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
         *         &lt;element name="Pocet" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
         *         &lt;element name="Text" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}text" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "druhAkcie",
            "hodnota",
            "pocet",
            "text"
        })
        public static class Emise {

            @XmlElement(name = "Druh_akcie", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1")
            @XmlSchemaType(name = "string")
            protected DruhAkcie druhAkcie;
            @XmlElement(name = "Hodnota", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1")
            protected BigDecimal hodnota;
            @XmlElement(name = "Pocet", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1")
            protected Integer pocet;
            @XmlElement(name = "Text", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1")
            protected String text;

            /**
             * Gets the value of the druhAkcie property.
             * 
             * @return
             *     possible object is
             *     {@link DruhAkcie }
             *     
             */
            public DruhAkcie getDruhAkcie() {
                return druhAkcie;
            }

            /**
             * Sets the value of the druhAkcie property.
             * 
             * @param value
             *     allowed object is
             *     {@link DruhAkcie }
             *     
             */
            public void setDruhAkcie(DruhAkcie value) {
                this.druhAkcie = value;
            }

            /**
             * Gets the value of the hodnota property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getHodnota() {
                return hodnota;
            }

            /**
             * Sets the value of the hodnota property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setHodnota(BigDecimal value) {
                this.hodnota = value;
            }

            /**
             * Gets the value of the pocet property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getPocet() {
                return pocet;
            }

            /**
             * Sets the value of the pocet property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setPocet(Integer value) {
                this.pocet = value;
            }

            /**
             * Gets the value of the text property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getText() {
                return text;
            }

            /**
             * Sets the value of the text property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setText(String value) {
                this.text = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Text" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}text" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "text"
    })
    public static class VycetNadacnihoMajetku {

        @XmlElement(name = "Text", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1", required = true)
        protected List<String> text;

        /**
         * Gets the value of the text property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the text property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getText().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getText() {
            if (text == null) {
                text = new ArrayList<String>();
            }
            return this.text;
        }

    }

}
