//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.29 at 07:54:38 PM CEST 
//


package cz.stuchlikova.ares.standard.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Tabulka pro uložení logických klíčů
 * 
 * <p>Java class for k_klic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="k_klic"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Cislo_soudu" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="Cislo_senatu" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="Cislo_znacky" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="Rok_znacky" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="Konkurz_vyrovnani" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}konkurz_vyrovnani_CEU"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "k_klic", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1", propOrder = {
    "cisloSoudu",
    "cisloSenatu",
    "cisloZnacky",
    "rokZnacky",
    "konkurzVyrovnani"
})
public class KKlic {

    @XmlElement(name = "Cislo_soudu")
    protected short cisloSoudu;
    @XmlElement(name = "Cislo_senatu")
    protected Short cisloSenatu;
    @XmlElement(name = "Cislo_znacky")
    protected short cisloZnacky;
    @XmlElement(name = "Rok_znacky")
    protected short rokZnacky;
    @XmlElement(name = "Konkurz_vyrovnani", required = true)
    @XmlSchemaType(name = "string")
    protected KonkurzVyrovnaniCEU konkurzVyrovnani;

    /**
     * Gets the value of the cisloSoudu property.
     * 
     */
    public short getCisloSoudu() {
        return cisloSoudu;
    }

    /**
     * Sets the value of the cisloSoudu property.
     * 
     */
    public void setCisloSoudu(short value) {
        this.cisloSoudu = value;
    }

    /**
     * Gets the value of the cisloSenatu property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCisloSenatu() {
        return cisloSenatu;
    }

    /**
     * Sets the value of the cisloSenatu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCisloSenatu(Short value) {
        this.cisloSenatu = value;
    }

    /**
     * Gets the value of the cisloZnacky property.
     * 
     */
    public short getCisloZnacky() {
        return cisloZnacky;
    }

    /**
     * Sets the value of the cisloZnacky property.
     * 
     */
    public void setCisloZnacky(short value) {
        this.cisloZnacky = value;
    }

    /**
     * Gets the value of the rokZnacky property.
     * 
     */
    public short getRokZnacky() {
        return rokZnacky;
    }

    /**
     * Sets the value of the rokZnacky property.
     * 
     */
    public void setRokZnacky(short value) {
        this.rokZnacky = value;
    }

    /**
     * Gets the value of the konkurzVyrovnani property.
     * 
     * @return
     *     possible object is
     *     {@link KonkurzVyrovnaniCEU }
     *     
     */
    public KonkurzVyrovnaniCEU getKonkurzVyrovnani() {
        return konkurzVyrovnani;
    }

    /**
     * Sets the value of the konkurzVyrovnani property.
     * 
     * @param value
     *     allowed object is
     *     {@link KonkurzVyrovnaniCEU }
     *     
     */
    public void setKonkurzVyrovnani(KonkurzVyrovnaniCEU value) {
        this.konkurzVyrovnani = value;
    }

}
