//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.24 at 03:40:11 PM CET 
//


package cz.stuchlikova.ares.standard.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Údaje o zakladatelích resp. zřizovatelích
 * 
 * <p>Java class for puvod_vzniku complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="puvod_vzniku"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Zakladatele_SP" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}zakladatele_SP"/&gt;
 *         &lt;element name="Zakladatele_OPS" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}zakladatele_OPS"/&gt;
 *         &lt;element name="Zrizovatele_OZ" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}zrizovatele_OZ"/&gt;
 *         &lt;element name="Zrizovatele_nadace" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}zrizovatele_nadace"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "puvod_vzniku", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1", propOrder = {
    "zakladateleSP",
    "zakladateleOPS",
    "zrizovateleOZ",
    "zrizovateleNadace"
})
public class PuvodVzniku {

    @XmlElement(name = "Zakladatele_SP")
    protected ZakladateleSP zakladateleSP;
    @XmlElement(name = "Zakladatele_OPS")
    protected ZakladateleOPS zakladateleOPS;
    @XmlElement(name = "Zrizovatele_OZ")
    protected ZrizovateleOZ zrizovateleOZ;
    @XmlElement(name = "Zrizovatele_nadace")
    protected ZrizovateleNadace zrizovateleNadace;

    /**
     * Gets the value of the zakladateleSP property.
     * 
     * @return
     *     possible object is
     *     {@link ZakladateleSP }
     *     
     */
    public ZakladateleSP getZakladateleSP() {
        return zakladateleSP;
    }

    /**
     * Sets the value of the zakladateleSP property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZakladateleSP }
     *     
     */
    public void setZakladateleSP(ZakladateleSP value) {
        this.zakladateleSP = value;
    }

    /**
     * Gets the value of the zakladateleOPS property.
     * 
     * @return
     *     possible object is
     *     {@link ZakladateleOPS }
     *     
     */
    public ZakladateleOPS getZakladateleOPS() {
        return zakladateleOPS;
    }

    /**
     * Sets the value of the zakladateleOPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZakladateleOPS }
     *     
     */
    public void setZakladateleOPS(ZakladateleOPS value) {
        this.zakladateleOPS = value;
    }

    /**
     * Gets the value of the zrizovateleOZ property.
     * 
     * @return
     *     possible object is
     *     {@link ZrizovateleOZ }
     *     
     */
    public ZrizovateleOZ getZrizovateleOZ() {
        return zrizovateleOZ;
    }

    /**
     * Sets the value of the zrizovateleOZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZrizovateleOZ }
     *     
     */
    public void setZrizovateleOZ(ZrizovateleOZ value) {
        this.zrizovateleOZ = value;
    }

    /**
     * Gets the value of the zrizovateleNadace property.
     * 
     * @return
     *     possible object is
     *     {@link ZrizovateleNadace }
     *     
     */
    public ZrizovateleNadace getZrizovateleNadace() {
        return zrizovateleNadace;
    }

    /**
     * Sets the value of the zrizovateleNadace property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZrizovateleNadace }
     *     
     */
    public void setZrizovateleNadace(ZrizovateleNadace value) {
        this.zrizovateleNadace = value;
    }

}
