//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.15 at 10:09:56 PM CEST 
//


package cz.stuchlikova.ares.standard.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Statutární orgán
 * 
 * <p>Java class for statutarni_organ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statutarni_organ"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Typ_SO" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}popis" minOccurs="0"/&gt;
 *         &lt;element name="Clen_SO" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}clen_SO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Vedouci_OZ" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}angazma_FO" minOccurs="0"/&gt;
 *         &lt;element name="Text" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.1}text" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statutarni_organ", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1", propOrder = {
    "typSO",
    "clenSO",
    "vedouciOZ",
    "text"
})
public class StatutarniOrgan {

    @XmlElement(name = "Typ_SO")
    protected String typSO;
    @XmlElement(name = "Clen_SO")
    protected List<ClenSO> clenSO;
    @XmlElement(name = "Vedouci_OZ")
    protected AngazmaFO vedouciOZ;
    @XmlElement(name = "Text")
    protected String text;

    /**
     * Gets the value of the typSO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypSO() {
        return typSO;
    }

    /**
     * Sets the value of the typSO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypSO(String value) {
        this.typSO = value;
    }

    /**
     * Gets the value of the clenSO property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clenSO property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClenSO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClenSO }
     * 
     * 
     */
    public List<ClenSO> getClenSO() {
        if (clenSO == null) {
            clenSO = new ArrayList<ClenSO>();
        }
        return this.clenSO;
    }

    /**
     * Gets the value of the vedouciOZ property.
     * 
     * @return
     *     possible object is
     *     {@link AngazmaFO }
     *     
     */
    public AngazmaFO getVedouciOZ() {
        return vedouciOZ;
    }

    /**
     * Sets the value of the vedouciOZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngazmaFO }
     *     
     */
    public void setVedouciOZ(AngazmaFO value) {
        this.vedouciOZ = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

}
