//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.24 at 03:40:11 PM CET 
//


package cz.stuchlikova.ares.standard.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vypis_basic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vypis_basic"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ICO" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}ico"/&gt;
 *         &lt;element name="DIC" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}dic" minOccurs="0"/&gt;
 *         &lt;element name="Obchodni_firma" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}obchodni_firma"/&gt;
 *         &lt;element name="Pravni_forma" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}pravni_forma" minOccurs="0"/&gt;
 *         &lt;element name="Adresa_dorucovaci" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}adresa_dorucovaci" minOccurs="0"/&gt;
 *         &lt;element name="Adresa_ARES" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}adresa_ARES" minOccurs="0"/&gt;
 *         &lt;element name="Registrace_OR" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}registrace" minOccurs="0"/&gt;
 *         &lt;element name="Registrace_RZP" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}registrace_RZP" minOccurs="0"/&gt;
 *         &lt;element name="Stav_subjektu_OR" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}stav" minOccurs="0"/&gt;
 *         &lt;element name="Stav_subjektu_CEU" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}stav_subjektu_ceu" minOccurs="0"/&gt;
 *         &lt;element name="Kategorie_poctu_pracovniku" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}kategorie_poctu_pracovniku" minOccurs="0"/&gt;
 *         &lt;element name="OKECE" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}okec" minOccurs="0"/&gt;
 *         &lt;element name="Predmety_podnikani" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}predmety_podnikani" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vypis_basic", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1", propOrder = {
    "ico",
    "dic",
    "obchodniFirma",
    "pravniForma",
    "adresaDorucovaci",
    "adresaARES",
    "registraceOR",
    "registraceRZP",
    "stavSubjektuOR",
    "stavSubjektuCEU",
    "kategoriePoctuPracovniku",
    "okece",
    "predmetyPodnikani"
})
public class VypisBasic {

    @XmlElement(name = "ICO", required = true)
    protected Ico ico;
    @XmlElement(name = "DIC")
    protected Dic dic;
    @XmlElement(name = "Obchodni_firma", required = true)
    protected ObchodniFirma obchodniFirma;
    @XmlElement(name = "Pravni_forma")
    protected PravniForma pravniForma;
    @XmlElement(name = "Adresa_dorucovaci")
    protected AdresaDorucovaci adresaDorucovaci;
    @XmlElement(name = "Adresa_ARES")
    protected AdresaARES adresaARES;
    @XmlElement(name = "Registrace_OR")
    protected Registrace registraceOR;
    @XmlElement(name = "Registrace_RZP")
    protected RegistraceRZP registraceRZP;
    @XmlElement(name = "Stav_subjektu_OR")
    protected Stav stavSubjektuOR;
    @XmlElement(name = "Stav_subjektu_CEU")
    protected StavSubjektuCeu stavSubjektuCEU;
    @XmlElement(name = "Kategorie_poctu_pracovniku")
    protected KategoriePoctuPracovniku kategoriePoctuPracovniku;
    @XmlElement(name = "OKECE")
    protected Okec okece;
    @XmlElement(name = "Predmety_podnikani")
    protected PredmetyPodnikani predmetyPodnikani;

    /**
     * Gets the value of the ico property.
     * 
     * @return
     *     possible object is
     *     {@link Ico }
     *     
     */
    public Ico getICO() {
        return ico;
    }

    /**
     * Sets the value of the ico property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ico }
     *     
     */
    public void setICO(Ico value) {
        this.ico = value;
    }

    /**
     * Gets the value of the dic property.
     * 
     * @return
     *     possible object is
     *     {@link Dic }
     *     
     */
    public Dic getDIC() {
        return dic;
    }

    /**
     * Sets the value of the dic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dic }
     *     
     */
    public void setDIC(Dic value) {
        this.dic = value;
    }

    /**
     * Gets the value of the obchodniFirma property.
     * 
     * @return
     *     possible object is
     *     {@link ObchodniFirma }
     *     
     */
    public ObchodniFirma getObchodniFirma() {
        return obchodniFirma;
    }

    /**
     * Sets the value of the obchodniFirma property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObchodniFirma }
     *     
     */
    public void setObchodniFirma(ObchodniFirma value) {
        this.obchodniFirma = value;
    }

    /**
     * Gets the value of the pravniForma property.
     * 
     * @return
     *     possible object is
     *     {@link PravniForma }
     *     
     */
    public PravniForma getPravniForma() {
        return pravniForma;
    }

    /**
     * Sets the value of the pravniForma property.
     * 
     * @param value
     *     allowed object is
     *     {@link PravniForma }
     *     
     */
    public void setPravniForma(PravniForma value) {
        this.pravniForma = value;
    }

    /**
     * Gets the value of the adresaDorucovaci property.
     * 
     * @return
     *     possible object is
     *     {@link AdresaDorucovaci }
     *     
     */
    public AdresaDorucovaci getAdresaDorucovaci() {
        return adresaDorucovaci;
    }

    /**
     * Sets the value of the adresaDorucovaci property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdresaDorucovaci }
     *     
     */
    public void setAdresaDorucovaci(AdresaDorucovaci value) {
        this.adresaDorucovaci = value;
    }

    /**
     * Gets the value of the adresaARES property.
     * 
     * @return
     *     possible object is
     *     {@link AdresaARES }
     *     
     */
    public AdresaARES getAdresaARES() {
        return adresaARES;
    }

    /**
     * Sets the value of the adresaARES property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdresaARES }
     *     
     */
    public void setAdresaARES(AdresaARES value) {
        this.adresaARES = value;
    }

    /**
     * Gets the value of the registraceOR property.
     * 
     * @return
     *     possible object is
     *     {@link Registrace }
     *     
     */
    public Registrace getRegistraceOR() {
        return registraceOR;
    }

    /**
     * Sets the value of the registraceOR property.
     * 
     * @param value
     *     allowed object is
     *     {@link Registrace }
     *     
     */
    public void setRegistraceOR(Registrace value) {
        this.registraceOR = value;
    }

    /**
     * Gets the value of the registraceRZP property.
     * 
     * @return
     *     possible object is
     *     {@link RegistraceRZP }
     *     
     */
    public RegistraceRZP getRegistraceRZP() {
        return registraceRZP;
    }

    /**
     * Sets the value of the registraceRZP property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegistraceRZP }
     *     
     */
    public void setRegistraceRZP(RegistraceRZP value) {
        this.registraceRZP = value;
    }

    /**
     * Gets the value of the stavSubjektuOR property.
     * 
     * @return
     *     possible object is
     *     {@link Stav }
     *     
     */
    public Stav getStavSubjektuOR() {
        return stavSubjektuOR;
    }

    /**
     * Sets the value of the stavSubjektuOR property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stav }
     *     
     */
    public void setStavSubjektuOR(Stav value) {
        this.stavSubjektuOR = value;
    }

    /**
     * Gets the value of the stavSubjektuCEU property.
     * 
     * @return
     *     possible object is
     *     {@link StavSubjektuCeu }
     *     
     */
    public StavSubjektuCeu getStavSubjektuCEU() {
        return stavSubjektuCEU;
    }

    /**
     * Sets the value of the stavSubjektuCEU property.
     * 
     * @param value
     *     allowed object is
     *     {@link StavSubjektuCeu }
     *     
     */
    public void setStavSubjektuCEU(StavSubjektuCeu value) {
        this.stavSubjektuCEU = value;
    }

    /**
     * Gets the value of the kategoriePoctuPracovniku property.
     * 
     * @return
     *     possible object is
     *     {@link KategoriePoctuPracovniku }
     *     
     */
    public KategoriePoctuPracovniku getKategoriePoctuPracovniku() {
        return kategoriePoctuPracovniku;
    }

    /**
     * Sets the value of the kategoriePoctuPracovniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link KategoriePoctuPracovniku }
     *     
     */
    public void setKategoriePoctuPracovniku(KategoriePoctuPracovniku value) {
        this.kategoriePoctuPracovniku = value;
    }

    /**
     * Gets the value of the okece property.
     * 
     * @return
     *     possible object is
     *     {@link Okec }
     *     
     */
    public Okec getOKECE() {
        return okece;
    }

    /**
     * Sets the value of the okece property.
     * 
     * @param value
     *     allowed object is
     *     {@link Okec }
     *     
     */
    public void setOKECE(Okec value) {
        this.okece = value;
    }

    /**
     * Gets the value of the predmetyPodnikani property.
     * 
     * @return
     *     possible object is
     *     {@link PredmetyPodnikani }
     *     
     */
    public PredmetyPodnikani getPredmetyPodnikani() {
        return predmetyPodnikani;
    }

    /**
     * Sets the value of the predmetyPodnikani property.
     * 
     * @param value
     *     allowed object is
     *     {@link PredmetyPodnikani }
     *     
     */
    public void setPredmetyPodnikani(PredmetyPodnikani value) {
        this.predmetyPodnikani = value;
    }

}
