//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.29 at 07:54:38 PM CEST 
//


package cz.stuchlikova.ares.standard.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Výpis z obchodního rejstříku podle ARES
 * 
 * <p>Java class for vypis_OR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vypis_OR"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Uvod" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}uvod" minOccurs="0"/&gt;
 *         &lt;element name="Zakladni_udaje" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}zakladni_udaje_OR"/&gt;
 *         &lt;element name="Registrace" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}registrace"/&gt;
 *         &lt;element name="Cinnost" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}cinnost" minOccurs="0"/&gt;
 *         &lt;element name="Ostatni_skutecnosti" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}ostatni_skutecnosti" minOccurs="0"/&gt;
 *         &lt;element name="Kapital" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}kapital" minOccurs="0"/&gt;
 *         &lt;element name="Statutarni_organ" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}statutarni_organ" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Likvidace" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}likvidace" minOccurs="0"/&gt;
 *         &lt;element name="Prokura" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}prokura" minOccurs="0"/&gt;
 *         &lt;element name="Dozorci_rada" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}dozorci_rada" minOccurs="0"/&gt;
 *         &lt;element name="Revizor" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}angazma_FO" minOccurs="0"/&gt;
 *         &lt;element name="Jediny_akcionar" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}angazma_PO_n_FO" minOccurs="0"/&gt;
 *         &lt;element name="Spolecnici" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}spolecnici" minOccurs="0"/&gt;
 *         &lt;element name="Puvod_vzniku" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}puvod_vzniku" minOccurs="0"/&gt;
 *         &lt;element name="Odstepne_zavody" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}odstepne_zavody" minOccurs="0"/&gt;
 *         &lt;element name="Konkurzy_vyrovnani" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1}konkurzy_vyrovnani" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vypis_OR", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1", propOrder = {
    "uvod",
    "zakladniUdaje",
    "registrace",
    "cinnost",
    "ostatniSkutecnosti",
    "kapital",
    "statutarniOrgan",
    "likvidace",
    "prokura",
    "dozorciRada",
    "revizor",
    "jedinyAkcionar",
    "spolecnici",
    "puvodVzniku",
    "odstepneZavody",
    "konkurzyVyrovnani"
})
public class VypisOR {

    @XmlElement(name = "Uvod")
    protected Uvod uvod;
    @XmlElement(name = "Zakladni_udaje", required = true)
    protected ZakladniUdajeOR zakladniUdaje;
    @XmlElement(name = "Registrace", required = true)
    protected Registrace registrace;
    @XmlElement(name = "Cinnost")
    protected Cinnost cinnost;
    @XmlElement(name = "Ostatni_skutecnosti")
    protected OstatniSkutecnosti ostatniSkutecnosti;
    @XmlElement(name = "Kapital")
    protected Kapital kapital;
    @XmlElement(name = "Statutarni_organ")
    protected List<StatutarniOrgan> statutarniOrgan;
    @XmlElement(name = "Likvidace")
    protected Likvidace likvidace;
    @XmlElement(name = "Prokura")
    protected Prokura prokura;
    @XmlElement(name = "Dozorci_rada")
    protected DozorciRada dozorciRada;
    @XmlElement(name = "Revizor")
    protected AngazmaFO revizor;
    @XmlElement(name = "Jediny_akcionar")
    protected AngazmaPONFO jedinyAkcionar;
    @XmlElement(name = "Spolecnici")
    protected Spolecnici spolecnici;
    @XmlElement(name = "Puvod_vzniku")
    protected PuvodVzniku puvodVzniku;
    @XmlElement(name = "Odstepne_zavody")
    protected OdstepneZavody odstepneZavody;
    @XmlElement(name = "Konkurzy_vyrovnani")
    protected KonkurzyVyrovnani konkurzyVyrovnani;

    /**
     * Gets the value of the uvod property.
     * 
     * @return
     *     possible object is
     *     {@link Uvod }
     *     
     */
    public Uvod getUvod() {
        return uvod;
    }

    /**
     * Sets the value of the uvod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uvod }
     *     
     */
    public void setUvod(Uvod value) {
        this.uvod = value;
    }

    /**
     * Gets the value of the zakladniUdaje property.
     * 
     * @return
     *     possible object is
     *     {@link ZakladniUdajeOR }
     *     
     */
    public ZakladniUdajeOR getZakladniUdaje() {
        return zakladniUdaje;
    }

    /**
     * Sets the value of the zakladniUdaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZakladniUdajeOR }
     *     
     */
    public void setZakladniUdaje(ZakladniUdajeOR value) {
        this.zakladniUdaje = value;
    }

    /**
     * Gets the value of the registrace property.
     * 
     * @return
     *     possible object is
     *     {@link Registrace }
     *     
     */
    public Registrace getRegistrace() {
        return registrace;
    }

    /**
     * Sets the value of the registrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Registrace }
     *     
     */
    public void setRegistrace(Registrace value) {
        this.registrace = value;
    }

    /**
     * Gets the value of the cinnost property.
     * 
     * @return
     *     possible object is
     *     {@link Cinnost }
     *     
     */
    public Cinnost getCinnost() {
        return cinnost;
    }

    /**
     * Sets the value of the cinnost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cinnost }
     *     
     */
    public void setCinnost(Cinnost value) {
        this.cinnost = value;
    }

    /**
     * Gets the value of the ostatniSkutecnosti property.
     * 
     * @return
     *     possible object is
     *     {@link OstatniSkutecnosti }
     *     
     */
    public OstatniSkutecnosti getOstatniSkutecnosti() {
        return ostatniSkutecnosti;
    }

    /**
     * Sets the value of the ostatniSkutecnosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link OstatniSkutecnosti }
     *     
     */
    public void setOstatniSkutecnosti(OstatniSkutecnosti value) {
        this.ostatniSkutecnosti = value;
    }

    /**
     * Gets the value of the kapital property.
     * 
     * @return
     *     possible object is
     *     {@link Kapital }
     *     
     */
    public Kapital getKapital() {
        return kapital;
    }

    /**
     * Sets the value of the kapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kapital }
     *     
     */
    public void setKapital(Kapital value) {
        this.kapital = value;
    }

    /**
     * Gets the value of the statutarniOrgan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statutarniOrgan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatutarniOrgan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatutarniOrgan }
     * 
     * 
     */
    public List<StatutarniOrgan> getStatutarniOrgan() {
        if (statutarniOrgan == null) {
            statutarniOrgan = new ArrayList<StatutarniOrgan>();
        }
        return this.statutarniOrgan;
    }

    /**
     * Gets the value of the likvidace property.
     * 
     * @return
     *     possible object is
     *     {@link Likvidace }
     *     
     */
    public Likvidace getLikvidace() {
        return likvidace;
    }

    /**
     * Sets the value of the likvidace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Likvidace }
     *     
     */
    public void setLikvidace(Likvidace value) {
        this.likvidace = value;
    }

    /**
     * Gets the value of the prokura property.
     * 
     * @return
     *     possible object is
     *     {@link Prokura }
     *     
     */
    public Prokura getProkura() {
        return prokura;
    }

    /**
     * Sets the value of the prokura property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prokura }
     *     
     */
    public void setProkura(Prokura value) {
        this.prokura = value;
    }

    /**
     * Gets the value of the dozorciRada property.
     * 
     * @return
     *     possible object is
     *     {@link DozorciRada }
     *     
     */
    public DozorciRada getDozorciRada() {
        return dozorciRada;
    }

    /**
     * Sets the value of the dozorciRada property.
     * 
     * @param value
     *     allowed object is
     *     {@link DozorciRada }
     *     
     */
    public void setDozorciRada(DozorciRada value) {
        this.dozorciRada = value;
    }

    /**
     * Gets the value of the revizor property.
     * 
     * @return
     *     possible object is
     *     {@link AngazmaFO }
     *     
     */
    public AngazmaFO getRevizor() {
        return revizor;
    }

    /**
     * Sets the value of the revizor property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngazmaFO }
     *     
     */
    public void setRevizor(AngazmaFO value) {
        this.revizor = value;
    }

    /**
     * Gets the value of the jedinyAkcionar property.
     * 
     * @return
     *     possible object is
     *     {@link AngazmaPONFO }
     *     
     */
    public AngazmaPONFO getJedinyAkcionar() {
        return jedinyAkcionar;
    }

    /**
     * Sets the value of the jedinyAkcionar property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngazmaPONFO }
     *     
     */
    public void setJedinyAkcionar(AngazmaPONFO value) {
        this.jedinyAkcionar = value;
    }

    /**
     * Gets the value of the spolecnici property.
     * 
     * @return
     *     possible object is
     *     {@link Spolecnici }
     *     
     */
    public Spolecnici getSpolecnici() {
        return spolecnici;
    }

    /**
     * Sets the value of the spolecnici property.
     * 
     * @param value
     *     allowed object is
     *     {@link Spolecnici }
     *     
     */
    public void setSpolecnici(Spolecnici value) {
        this.spolecnici = value;
    }

    /**
     * Gets the value of the puvodVzniku property.
     * 
     * @return
     *     possible object is
     *     {@link PuvodVzniku }
     *     
     */
    public PuvodVzniku getPuvodVzniku() {
        return puvodVzniku;
    }

    /**
     * Sets the value of the puvodVzniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link PuvodVzniku }
     *     
     */
    public void setPuvodVzniku(PuvodVzniku value) {
        this.puvodVzniku = value;
    }

    /**
     * Gets the value of the odstepneZavody property.
     * 
     * @return
     *     possible object is
     *     {@link OdstepneZavody }
     *     
     */
    public OdstepneZavody getOdstepneZavody() {
        return odstepneZavody;
    }

    /**
     * Sets the value of the odstepneZavody property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdstepneZavody }
     *     
     */
    public void setOdstepneZavody(OdstepneZavody value) {
        this.odstepneZavody = value;
    }

    /**
     * Gets the value of the konkurzyVyrovnani property.
     * 
     * @return
     *     possible object is
     *     {@link KonkurzyVyrovnani }
     *     
     */
    public KonkurzyVyrovnani getKonkurzyVyrovnani() {
        return konkurzyVyrovnani;
    }

    /**
     * Sets the value of the konkurzyVyrovnani property.
     * 
     * @param value
     *     allowed object is
     *     {@link KonkurzyVyrovnani }
     *     
     */
    public void setKonkurzyVyrovnani(KonkurzyVyrovnani value) {
        this.konkurzyVyrovnani = value;
    }

}
