//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.10 at 07:21:26 PM CET 
//


package cz.stuchlikova.ares.standard.stub;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for zdroj_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="zdroj_type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;minLength value="2"/&gt;
 *     &lt;maxLength value="5"/&gt;
 *     &lt;enumeration value="ARES"/&gt;
 *     &lt;enumeration value="OR"/&gt;
 *     &lt;enumeration value="RES"/&gt;
 *     &lt;enumeration value="RZP"/&gt;
 *     &lt;enumeration value="RZZ"/&gt;
 *     &lt;enumeration value="DPH"/&gt;
 *     &lt;enumeration value="DS"/&gt;
 *     &lt;enumeration value="SCP"/&gt;
 *     &lt;enumeration value="CEU"/&gt;
 *     &lt;enumeration value="CEDR"/&gt;
 *     &lt;enumeration value="RARIS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "zdroj_type", namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.1")
@XmlEnum
public enum ZdrojType {

    ARES,
    OR,
    RES,
    RZP,
    RZZ,
    DPH,
    DS,
    SCP,
    CEU,
    CEDR,
    RARIS;

    public String value() {
        return name();
    }

    public static ZdrojType fromValue(String v) {
        return valueOf(v);
    }

}
